from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List

from .models import SnapshotDIDInfo


_SUFFIX_NOISE = [
    r"\s+at\s+Last\s+Fault\s+Code\s+Set\s*$",
    r"\s+at\s+Fault\s+Code\s+Set\s*$",
    r"\s+Last\s+Fault\s+Code\s+Set\s*$",
]


def build_snapshot_c_filename(did: SnapshotDIDInfo) -> str:
    suffix = _clean_name(did.did_name_en)
    return f"RBAPLCUST_19Snapshot_{did.did_hex[2:]}_{suffix}.c"


def build_snapshot_c_content(did: SnapshotDIDInfo, record_numbers: List[str]) -> str:
    file_name = build_snapshot_c_filename(did)
    short_name = did.read_fnc.replace("_ReadData", "")
    lines = [
        "/**",
        " * @ingroup 'RBAPLCust'",
        " *",
        f" * {file_name}",
        " * Generated by 19service-toolkit -- do not edit by hand.",
        " *",
        " * \\copyright",
        " * Robert Bosch GmbH reserves all rights even in the event of industrial property rights.",
        " * We reserve all rights of disposal such as copying and passing on to third parties.",
        " */",
        "",
        "/* USED_INTERFACES: */",
        '#include "Dcm.h"',
        '#include "Dcm_Lcfg_DspUds.h"',
        "",
        "/* REALIZED_INTERFACES: */",
        '#include "RBAPLCust_Config.h"',
        '#include "RBMESG_Explicit.h"',
        '#include "RBAPLCUST_Global.h"',
        "",
        "",
        f"/* Snapshot DID  : {did.did_hex}",
        f" * ShortName    : {short_name}",
        f" * Size         : {did.size_bytes} bytes",
        f" * Product Type : {did.product_type}",
        f" * Record Nos   : {', '.join(record_numbers)}",
        " */",
        "",
        f"Std_ReturnType {did.read_fnc}(uint8* Data)",
        "{",
        "    /* TODO(agent): implement snapshot data read body.",
        "     *",
        "     * --- Identity ---",
        f"     * service    : 19 (ReadDTCInformation)",
        f"     * subfunction: 0x04 (reportDTCSnapshotRecordByDTCNumber)",
        f"     * did_hex    : {did.did_hex}",
        f"     * did_name   : {did.did_name_en}",
        f"     * size_bytes : {did.size_bytes}",
        f"     * read_fnc   : {did.read_fnc}",
        f"     * impl_signal_list: {did.impl_signal_list or '<empty>'}",
        f"     * impl_notes  : {did.impl_notes or '<empty>'}",
        "     *",
        "     * --- Snapshot data source hint ---",
        f"     * Pattern: {_guess_pattern(did.did_name_en)}",
        "     *",
        "     * --- Typical implementation pattern ---",
    ]
    for pattern_line in _render_pattern_hint_lines(did.did_name_en):
        lines.append(f"     * {pattern_line}")
    lines.append("     *")
    lines.append("     * --- Sub-field layout ---")
    for sf_line in _render_sub_fields(did):
        lines.append(f"     * {sf_line}")
    lines.extend([
        "     *",
        "     * --- Style constraints ---",
        "     * - MISRA-C compliant: one statement per line, explicit casts,",
        "     *   every return path assigned, no implicit precision loss.",
        "     * - If using DefineMESGDef/RcvMESGDef or RBMESG_DefineMESGDef/",
        "     *   RBMESG_RcvMESGDef pairs, both macros must appear and must be",
        "     *   the first statements inside the enclosing #if guard.",
        "     *",
        "     * Action: replace this TODO block with the real body, then",
        "     * return E_OK. Leave the block in place if the data source is",
        "     * not yet known. */",
        "    (void)Data;",
        "",
        "    return E_NOT_OK;",
        "}",
        "",
    ])
    return "\n".join(lines)


def try_build_real_snapshot_c_content(did: SnapshotDIDInfo, record_numbers: List[str]) -> str | None:
    """Return a concrete implementation when the input is unambiguous.

    Phase 3 intentionally stays conservative.  At the moment only a single
    getter-call source is implemented automatically.  Everything else keeps the
    TODO stub until the user input and signal analysis are extended further.
    """
    items = [item.strip() for item in did.impl_signal_list.split(";") if item.strip()]
    if len(items) == 1 and items[0].endswith(")"):
        return _build_getter_impl_content(did, record_numbers, items[0])

    if _can_build_scalar_copy_sequence(items):
        return _build_scalar_copy_sequence_content(did, record_numbers, items)

    if _can_build_single_byte_bit_pack(did, items):
        return _build_single_byte_bit_pack_content(did, record_numbers, items)

    if _can_build_struct_be_with_qualifier_and_scaling(did, items):
        return _build_struct_be_with_qualifier_and_scaling_content(did, record_numbers, items)

    if _can_build_struct_be_with_qualifier(did, items):
        return _build_struct_be_with_qualifier_content(did, record_numbers, items)

    notes = (did.impl_notes or "").lower()
    if did.size_bytes == 1 and len(items) == 2 and all(not item.endswith(")") and "." not in item for item in items):
        if "low nibble" in notes and "high nibble" in notes:
            return _build_simple_nibble_pack_content(did, record_numbers, items)

    if _can_build_simple_nibble_pack(did, items):
        return _build_simple_nibble_pack_content(did, record_numbers, items)

    return None


def _clean_name(name: str) -> str:
    for pattern in _SUFFIX_NOISE:
        name = re.sub(pattern, "", name, flags=re.IGNORECASE)
    words = re.split(r"[^A-Za-z0-9]+", name)
    return "".join(w[:1].upper() + w[1:] for w in words if w)


def _build_getter_impl_content(did: SnapshotDIDInfo, record_numbers: List[str], getter_call: str) -> str:
    file_name = build_snapshot_c_filename(did)
    short_name = did.read_fnc.replace("_ReadData", "")
    local_name = _guess_local_name(getter_call)
    value_type = "uint16"
    transform_expr = _guess_getter_transform(did, local_name)
    return "\n".join([
        "/**",
        " * @ingroup 'RBAPLCust'",
        " *",
        f" * {file_name}",
        " * Generated by 19service-toolkit -- do not edit by hand.",
        " *",
        " * \\copyright",
        " * Robert Bosch GmbH reserves all rights even in the event of industrial property rights.",
        " * We reserve all rights of disposal such as copying and passing on to third parties.",
        " */",
        "",
        "/* USED_INTERFACES: */",
        '#include "Dcm.h"',
        '#include "Dcm_Lcfg_DspUds.h"',
        "",
        "/* REALIZED_INTERFACES: */",
        '#include "RBAPLCust_Config.h"',
        '#include "RBMESG_Explicit.h"',
        '#include "RBAPLCUST_Global.h"',
        "",
        "",
        f"/* Snapshot DID  : {did.did_hex}",
        f" * ShortName    : {short_name}",
        f" * Size         : {did.size_bytes} bytes",
        f" * Product Type : {did.product_type}",
        f" * Record Nos   : {', '.join(record_numbers)}",
        " */",
        "",
        f"Std_ReturnType {did.read_fnc}(uint8* Data)",
        "{",
        f"    {value_type} {local_name};",
        "",
        f"    {local_name} = {getter_call};",
        f"    Data[0] = {transform_expr};",
        "",
        "    return E_OK;",
        "}",
        "",
    ])


def _guess_local_name(getter_call: str) -> str:
    base = getter_call.split("(", 1)[0].split("::")[-1]
    words = re.split(r"[^A-Za-z0-9]+", base)
    suffix = "".join(w[:1].upper() + w[1:] for w in words if w)
    return f"l_{suffix}" if suffix else "l_Value"


def _guess_getter_transform(did: SnapshotDIDInfo, local_name: str) -> str:
    # First supported template: single-byte battery/power-supply style scaling.
    lower = did.did_name_en.lower()
    if did.size_bytes == 1 and any(k in lower for k in ("battery", "voltage", "power supply")):
        return f"(uint8)(((({local_name} * 100u) / 256u)) >> 3u)"
    return f"(uint8)({local_name})"


def _can_build_scalar_copy_sequence(items: List[str]) -> bool:
    if not items:
        return False
    for item in items:
        if item.endswith(")"):
            return False
        if "." in item:
            return False
    return True


def _build_scalar_copy_sequence_content(did: SnapshotDIDInfo, record_numbers: List[str], items: List[str]) -> str:
    if did.size_bytes != len(items):
        return None

    file_name = build_snapshot_c_filename(did)
    short_name = did.read_fnc.replace("_ReadData", "")
    local_names = [_guess_signal_local_name(item) for item in items]
    lines = [
        "/**",
        " * @ingroup 'RBAPLCust'",
        " *",
        f" * {file_name}",
        " * Generated by 19service-toolkit -- do not edit by hand.",
        " *",
        " * \\copyright",
        " * Robert Bosch GmbH reserves all rights even in the event of industrial property rights.",
        " * We reserve all rights of disposal such as copying and passing on to third parties.",
        " */",
        "",
        "/* USED_INTERFACES: */",
        '#include "Dcm.h"',
        '#include "Dcm_Lcfg_DspUds.h"',
        "",
        "/* REALIZED_INTERFACES: */",
        '#include "RBAPLCust_Config.h"',
        '#include "RBMESG_Explicit.h"',
        '#include "RBAPLCUST_Global.h"',
        "",
        "",
        f"/* Snapshot DID  : {did.did_hex}",
        f" * ShortName    : {short_name}",
        f" * Size         : {did.size_bytes} bytes",
        f" * Product Type : {did.product_type}",
        f" * Record Nos   : {', '.join(record_numbers)}",
        " */",
        "",
        f"Std_ReturnType {did.read_fnc}(uint8* Data)",
        "{",
    ]

    for local_name in local_names:
        lines.append(f"    UBYTE {local_name};")
    lines.append("")

    for local_name, signal_name in zip(local_names, items):
        lines.append(f"    RcvMESG({local_name}, {signal_name});")
    lines.append("")

    for idx, local_name in enumerate(local_names):
        lines.append(f"    Data[{idx}] = {local_name};")
    lines.extend([
        "",
        "    return E_OK;",
        "}",
        "",
    ])
    return "\n".join(lines)


def _guess_signal_local_name(signal_name: str) -> str:
    tokens = re.split(r"[^A-Za-z0-9]+", signal_name)
    suffix = "_".join(token for token in tokens if token)
    return f"l_{suffix}" if suffix else "l_Value"


def _can_build_single_byte_bit_pack(did: SnapshotDIDInfo, items: List[str]) -> bool:
    if did.size_bytes != 1:
        return False
    if len(items) < 2:
        return False
    if any(item.endswith(")") or "." in item for item in items):
        return False
    notes = (did.impl_notes or "").lower()
    return all(f"bit{i}=" in notes for i in range(min(len(items), 6)))


def _build_single_byte_bit_pack_content(did: SnapshotDIDInfo, record_numbers: List[str], items: List[str]) -> str | None:
    file_name = build_snapshot_c_filename(did)
    short_name = did.read_fnc.replace("_ReadData", "")
    local_names = [_guess_signal_local_name(item) for item in items]
    expr_parts = []
    for idx, local_name in enumerate(local_names):
        if idx == 0:
            expr_parts.append(f"({local_name} != 0u ? 0x01u : 0x00u)")
        else:
            expr_parts.append(f"(({local_name} != 0u ? 0x01u : 0x00u) << {idx})")
    packed_expr = " | ".join(expr_parts) if expr_parts else "0x00u"

    lines = [
        "/**",
        " * @ingroup 'RBAPLCust'",
        " *",
        f" * {file_name}",
        " * Generated by 19service-toolkit -- do not edit by hand.",
        " *",
        " * \\copyright",
        " * Robert Bosch GmbH reserves all rights even in the event of industrial property rights.",
        " * We reserve all rights of disposal such as copying and passing on to third parties.",
        " */",
        "",
        "/* USED_INTERFACES: */",
        '#include "Dcm.h"',
        '#include "Dcm_Lcfg_DspUds.h"',
        "",
        "/* REALIZED_INTERFACES: */",
        '#include "RBAPLCust_Config.h"',
        '#include "RBMESG_Explicit.h"',
        '#include "RBAPLCUST_Global.h"',
        "",
        "",
        f"/* Snapshot DID  : {did.did_hex}",
        f" * ShortName    : {short_name}",
        f" * Size         : {did.size_bytes} bytes",
        f" * Product Type : {did.product_type}",
        f" * Record Nos   : {', '.join(record_numbers)}",
        " */",
        "",
        f"Std_ReturnType {did.read_fnc}(uint8* Data)",
        "{",
    ]

    for local_name in local_names:
        lines.append(f"    UBYTE {local_name};")
    lines.append("")

    for local_name, signal_name in zip(local_names, items):
        lines.append(f"    RcvMESG({local_name}, {signal_name});")
    lines.append("")
    lines.append(f"    Data[0] = (uint8)({packed_expr});")
    lines.extend([
        "",
        "    return E_OK;",
        "}",
        "",
    ])
    return "\n".join(lines)


def _build_mixed_pack_scaffold_content(did: SnapshotDIDInfo, record_numbers: List[str], items: List[str]) -> str:
    file_name = build_snapshot_c_filename(did)
    short_name = did.read_fnc.replace("_ReadData", "")
    signal_items = [item.strip() for item in items if item.strip()]
    lines = [
        "/**",
        " * @ingroup 'RBAPLCust'",
        " *",
        f" * {file_name}",
        " * Generated by 19service-toolkit -- do not edit by hand.",
        " *",
        " * \\copyright",
        " * Robert Bosch GmbH reserves all rights even in the event of industrial property rights.",
        " * We reserve all rights of disposal such as copying and passing on to third parties.",
        " */",
        "",
        "/* USED_INTERFACES: */",
        '#include "Dcm.h"',
        '#include "Dcm_Lcfg_DspUds.h"',
        "",
        "/* REALIZED_INTERFACES: */",
        '#include "RBAPLCust_Config.h"',
        '#include "RBMESG_Explicit.h"',
        '#include "RBAPLCUST_Global.h"',
        "",
        "",
        f"/* Snapshot DID  : {did.did_hex}",
        f" * ShortName    : {short_name}",
        f" * Size         : {did.size_bytes} bytes",
        f" * Product Type : {did.product_type}",
        f" * Record Nos   : {', '.join(record_numbers)}",
        " */",
        "",
        f"Std_ReturnType {did.read_fnc}(uint8* Data)",
        "{",
        "    /* TODO(agent): mixed-pack scaffold generated from implementation input.",
        "     * The user input and project evidence were sufficient to classify this DID as",
        "     * a mixed-source packed record, but not enough to safely finalize every packed",
        "     * bit/byte assignment automatically in this release.",
        "     *",
        "     * Source list:",
    ]
    for item in signal_items:
        lines.append(f"     *   - {item}")
    lines.extend([
        "     *",
        "     * Notes:",
        f"     *   {did.impl_notes or '<empty>'}",
        "     *",
        "     * Expected next action:",
        "     *   1. Search project for the listed signals/getters.",
        "     *   2. Determine receive style (RcvMESG / DefineMESGDef / RBMESG / direct field).",
        "     *   3. Implement byte0/byte1/byte2 packing exactly as described in impl_notes.",
        "     */",
        "    (void)Data;",
        "",
        "    return E_NOT_OK;",
        "}",
        "",
    ])
    return "\n".join(lines)


def _build_state_pack_scaffold_content(did: SnapshotDIDInfo, record_numbers: List[str], items: List[str]) -> str:
    file_name = build_snapshot_c_filename(did)
    short_name = did.read_fnc.replace("_ReadData", "")
    signal_items = [item.strip() for item in items if item.strip()]
    lines = [
        "/**",
        " * @ingroup 'RBAPLCust'",
        " *",
        f" * {file_name}",
        " * Generated by 19service-toolkit -- do not edit by hand.",
        " *",
        " * \\copyright",
        " * Robert Bosch GmbH reserves all rights even in the event of industrial property rights.",
        " * We reserve all rights of disposal such as copying and passing on to third parties.",
        " */",
        "",
        "/* USED_INTERFACES: */",
        '#include "Dcm.h"',
        '#include "Dcm_Lcfg_DspUds.h"',
        "",
        "/* REALIZED_INTERFACES: */",
        '#include "RBAPLCust_Config.h"',
        '#include "RBMESG_Explicit.h"',
        '#include "RBAPLCUST_Global.h"',
        "",
        "",
        f"/* Snapshot DID  : {did.did_hex}",
        f" * ShortName    : {short_name}",
        f" * Size         : {did.size_bytes} bytes",
        f" * Product Type : {did.product_type}",
        f" * Record Nos   : {', '.join(record_numbers)}",
        " */",
        "",
        f"Std_ReturnType {did.read_fnc}(uint8* Data)",
        "{",
        "    /* TODO(agent): state-pack scaffold generated from implementation input.",
        "     * The user input indicates a one-byte state/status mapping with condition-dependent",
        "     * packing, but the exact intermediate state derivation still requires project-style",
        "     * code search before emitting final logic safely.",
        "     *",
        "     * Source list:",
    ]
    for item in signal_items:
        lines.append(f"     *   - {item}")
    lines.extend([
        "     *",
        "     * Notes:",
        f"     *   {did.impl_notes or '<empty>'}",
        "     *",
        "     * Expected next action:",
        "     *   1. Search project for the listed signals and current state enums.",
        "     *   2. Derive intermediate operation / dynamic-apply states from the project logic.",
        "     *   3. Pack the final one-byte result exactly as described in impl_notes.",
        "     */",
        "    (void)Data;",
        "",
        "    return E_NOT_OK;",
        "}",
        "",
    ])
    return "\n".join(lines)


def _build_hybrid_three_byte_content(did: SnapshotDIDInfo, record_numbers: List[str], items: List[str]) -> str:
    file_name = build_snapshot_c_filename(did)
    short_name = did.read_fnc.replace("_ReadData", "")

    # Expected input shape for the current hybrid strategy:
    #   1) scalar signal for Data[0]
    #   2) struct field using Qualifier_N for Data[1]
    #   3) scalar/global signal for Data[2] with simple scaling hint in notes
    scalar0 = items[0]
    struct_item = items[1]
    scalar2 = items[2] if len(items) > 2 else ""
    container, field = struct_item.split(".", 1)
    local0 = _guess_signal_local_name(scalar0)
    local_struct = _guess_struct_local_name(container)
    local2 = _guess_signal_local_name(scalar2) if scalar2 else "l_Value2"
    qualifier_valid = _guess_hybrid_valid_qualifier(did.impl_notes)

    lines = [
        "/**",
        " * @ingroup 'RBAPLCust'",
        " *",
        f" * {file_name}",
        " * Generated by 19service-toolkit -- do not edit by hand.",
        " *",
        " * \\copyright",
        " * Robert Bosch GmbH reserves all rights even in the event of industrial property rights.",
        " * We reserve all rights of disposal such as copying and passing on to third parties.",
        " */",
        "",
        "/* USED_INTERFACES: */",
        '#include "Dcm.h"',
        '#include "Dcm_Lcfg_DspUds.h"',
        "",
        "/* REALIZED_INTERFACES: */",
        '#include "RBAPLCust_Config.h"',
        '#include "RBMESG_Explicit.h"',
        '#include "RBAPLCUST_Global.h"',
        "",
        "",
        f"/* Snapshot DID  : {did.did_hex}",
        f" * ShortName    : {short_name}",
        f" * Size         : {did.size_bytes} bytes",
        f" * Product Type : {did.product_type}",
        f" * Record Nos   : {', '.join(record_numbers)}",
        " */",
        "",
        f"Std_ReturnType {did.read_fnc}(uint8* Data)",
        "{",
        f"    UBYTE {local0};",
        f"    UBYTE {local2};",
        "",
        f"    DefineMESGDef({container});",
        f"    RcvMESGDef({container});",
        f"    RcvMESG({local0}, {scalar0});",
        f"    RcvMESG({local2}, {scalar2});",
        "",
        f"    Data[0] = {local0};",
        f"    if ({local_struct}.Qualifier_N == {qualifier_valid})",
        "    {",
        f"        Data[1] = {local_struct}.{field};",
        "    }",
        "    else",
        "    {",
        "        Data[1] = 0xFFu;",
        "    }",
        f"    Data[2] = (uint8)({local2}); /* TODO(agent): apply any required scaling from impl_notes */",
        "",
        "    return E_OK;",
        "}",
        "",
    ]
    return "\n".join(lines)


def _guess_hybrid_valid_qualifier(notes: str) -> str:
    m = re.search(r"qualifier_n\s*=\s*([A-Za-z0-9_]+)", notes, flags=re.IGNORECASE)
    if m:
        return m.group(1)
    return "0u /* TODO(agent): confirm valid qualifier enum */"


def _can_build_struct_be_with_qualifier_and_scaling(did: SnapshotDIDInfo, items: List[str]) -> bool:
    if did.size_bytes < 2:
        return False
    if not items:
        return False
    if not all("." in item and not item.endswith(")") for item in items):
        return False
    notes = (did.impl_notes or "").lower()
    return "qualifier" in notes and "scaling" in notes and "offset" in notes


def _build_struct_be_with_qualifier_and_scaling_content(did: SnapshotDIDInfo, record_numbers: List[str], items: List[str]) -> str | None:
    if did.size_bytes != len(items) * 2:
        return None

    file_name = build_snapshot_c_filename(did)
    short_name = did.read_fnc.replace("_ReadData", "")
    locals_info = []
    effective_sub_fields = [sf for sf in did.sub_fields if sf.get("name_en")]
    for idx, item in enumerate(items):
        container, field = item.split(".", 1)
        local_name = _guess_struct_local_name(container)
        qualifier_values = _guess_valid_qualifier_values(container)
        sf = effective_sub_fields[idx] if idx < len(effective_sub_fields) else {}
        scaled_name = f"l_Temp_{_clean_name(sf.get('name_en', field))}_SW"
        locals_info.append((container, field, local_name, qualifier_values, sf, scaled_name))

    lines = [
        "/**",
        " * @ingroup 'RBAPLCust'",
        " *",
        f" * {file_name}",
        " * Generated by 19service-toolkit -- do not edit by hand.",
        " *",
        " * \\copyright",
        " * Robert Bosch GmbH reserves all rights even in the event of industrial property rights.",
        " * We reserve all rights of disposal such as copying and passing on to third parties.",
        " */",
        "",
        "/* USED_INTERFACES: */",
        '#include "Dcm.h"',
        '#include "Dcm_Lcfg_DspUds.h"',
        "",
        "/* REALIZED_INTERFACES: */",
        '#include "RBAPLCust_Config.h"',
        '#include "RBMESG_Explicit.h"',
        '#include "RBAPLCUST_Global.h"',
        "",
        "",
        f"/* Snapshot DID  : {did.did_hex}",
        f" * ShortName    : {short_name}",
        f" * Size         : {did.size_bytes} bytes",
        f" * Product Type : {did.product_type}",
        f" * Record Nos   : {', '.join(record_numbers)}",
        " */",
        "",
        f"Std_ReturnType {did.read_fnc}(uint8* Data)",
        "{",
    ]

    for _, _, _, _, _, scaled_name in locals_info:
        lines.append(f"    sint16 {scaled_name};")
    lines.append("")

    for container, _, _, _, _, _ in locals_info:
        lines.append(f"    DefineMESGDef({container});")
    lines.append("")
    for container, _, _, _, _, _ in locals_info:
        lines.append(f"    RcvMESGDef({container});")
    lines.append("")

    data_idx = 0
    for _, field, local_name, qualifier_values, sf, scaled_name in locals_info:
        expr = _build_scaling_expr(local_name, field, sf)
        lines.append(f"    switch ({local_name}.Qualifier_N)")
        lines.append("    {")
        for val in qualifier_values:
            lines.append(f"        case {val}:")
        lines.append(f"            {scaled_name} = {expr};")
        lines.append(f"            Data[{data_idx}] = (uint8)({scaled_name} >> 8);")
        lines.append(f"            Data[{data_idx + 1}] = (uint8)({scaled_name});")
        lines.append("            break;")
        lines.append("")
        lines.append("        default:")
        lines.append(f"            Data[{data_idx}] = C_Default_FF_UB;")
        lines.append(f"            Data[{data_idx + 1}] = C_Default_FF_UB;")
        lines.append("            break;")
        lines.append("    }")
        lines.append("")
        data_idx += 2

    lines.extend([
        "    return E_OK;",
        "}",
        "",
    ])
    return "\n".join(lines)


def _build_scaling_expr(local_name: str, field: str, sf: Dict[str, str]) -> str:
    resolution = sf.get("resolution", "")
    offset = sf.get("offset", "")
    field_expr = f"{local_name}.{field}"

    # Keep the first version deliberately simple and explicit.  For now the
    # generated code documents the FSCS scaling intent rather than trying to
    # infer exact project-specific physics formulas from free text.
    if resolution and offset:
        return f"(sint16)({field_expr}) /* TODO(agent): apply resolution={resolution} offset={offset} exactly as project requires */"
    if offset:
        return f"(sint16)({field_expr}) /* TODO(agent): apply offset={offset} exactly as project requires */"
    return f"(sint16)({field_expr})"


def _can_build_struct_be_with_qualifier(did: SnapshotDIDInfo, items: List[str]) -> bool:
    if did.size_bytes < 2:
        return False
    if not items:
        return False
    if not all("." in item and not item.endswith(")") for item in items):
        return False
    notes = (did.impl_notes or "").lower()
    return "qualifier" in notes and "big-endian" in notes and "0xff" in notes


def _build_struct_be_with_qualifier_content(did: SnapshotDIDInfo, record_numbers: List[str], items: List[str]) -> str | None:
    if did.size_bytes != len(items) * 2:
        return None

    file_name = build_snapshot_c_filename(did)
    short_name = did.read_fnc.replace("_ReadData", "")
    locals_info = []
    for item in items:
        container, field = item.split(".", 1)
        local_name = _guess_struct_local_name(container)
        qualifier_values = _guess_valid_qualifier_values(container)
        locals_info.append((container, field, local_name, qualifier_values))

    lines = [
        "/**",
        " * @ingroup 'RBAPLCust'",
        " *",
        f" * {file_name}",
        " * Generated by 19service-toolkit -- do not edit by hand.",
        " *",
        " * \\copyright",
        " * Robert Bosch GmbH reserves all rights even in the event of industrial property rights.",
        " * We reserve all rights of disposal such as copying and passing on to third parties.",
        " */",
        "",
        "/* USED_INTERFACES: */",
        '#include "Dcm.h"',
        '#include "Dcm_Lcfg_DspUds.h"',
        "",
        "/* REALIZED_INTERFACES: */",
        '#include "RBAPLCust_Config.h"',
        '#include "RBMESG_Explicit.h"',
        '#include "RBAPLCUST_Global.h"',
        "",
        "",
        f"/* Snapshot DID  : {did.did_hex}",
        f" * ShortName    : {short_name}",
        f" * Size         : {did.size_bytes} bytes",
        f" * Product Type : {did.product_type}",
        f" * Record Nos   : {', '.join(record_numbers)}",
        " */",
        "",
        f"Std_ReturnType {did.read_fnc}(uint8* Data)",
        "{",
    ]

    for container, _, _, _ in locals_info:
        lines.append(f"    DefineMESGDef({container});")
    lines.append("")
    for container, _, _, _ in locals_info:
        lines.append(f"    RcvMESGDef({container});")
    lines.append("")

    data_idx = 0
    for _, field, local_name, qualifier_values in locals_info:
        lines.append(f"    switch ({local_name}.Qualifier_N)")
        lines.append("    {")
        for val in qualifier_values:
            lines.append(f"        case {val}:")
        lines.append(f"            Data[{data_idx}] = (uint8)({local_name}.{field} >> 8);")
        lines.append(f"            Data[{data_idx + 1}] = (uint8)({local_name}.{field});")
        lines.append("            break;")
        lines.append("")
        lines.append("        default:")
        lines.append(f"            Data[{data_idx}] = C_Default_FF_UB;")
        lines.append(f"            Data[{data_idx + 1}] = C_Default_FF_UB;")
        lines.append("            break;")
        lines.append("    }")
        lines.append("")
        data_idx += 2

    lines.extend([
        "    return E_OK;",
        "}",
        "",
    ])
    return "\n".join(lines)


def _guess_struct_local_name(container: str) -> str:
    return f"l_{container}"


def _guess_valid_qualifier_values(container: str) -> List[str]:
    lower = container.lower()
    if "wheelspeed" in lower:
        return [
            "C_WheelSpeedQualifier_Normal_N",
            "C_WheelSpeedQualifier_ReducedMonitored_N",
        ]
    if "vehiclespeed" in lower:
        return [
            "C_VehicleSpeedQualifier_Normal_N",
            "C_VehicleSpeedQualifier_DifferentCalculated_N",
            "C_VehicleSpeedQualifier_ReducedMonitored_N",
        ]
    return ["0 /* TODO(agent): confirm qualifier enum */"]


def _can_build_simple_nibble_pack(did: SnapshotDIDInfo, items: List[str]) -> bool:
    if did.size_bytes != 1:
        return False
    if len(items) != 2:
        return False
    if any(item.endswith(")") or "." in item for item in items):
        return False
    notes = (did.impl_notes or "").lower()
    return "low nibble" in notes and "high nibble" in notes


def _build_simple_nibble_pack_content(did: SnapshotDIDInfo, record_numbers: List[str], items: List[str]) -> str:
    file_name = build_snapshot_c_filename(did)
    short_name = did.read_fnc.replace("_ReadData", "")
    left_name = _guess_signal_local_name(items[0])
    right_name = _guess_signal_local_name(items[1])
    return "\n".join([
        "/**",
        " * @ingroup 'RBAPLCust'",
        " *",
        f" * {file_name}",
        " * Generated by 19service-toolkit -- do not edit by hand.",
        " *",
        " * \\copyright",
        " * Robert Bosch GmbH reserves all rights even in the event of industrial property rights.",
        " * We reserve all rights of disposal such as copying and passing on to third parties.",
        " */",
        "",
        "/* USED_INTERFACES: */",
        '#include "Dcm.h"',
        '#include "Dcm_Lcfg_DspUds.h"',
        "",
        "/* REALIZED_INTERFACES: */",
        '#include "RBAPLCust_Config.h"',
        '#include "RBMESG_Explicit.h"',
        '#include "RBAPLCUST_Global.h"',
        "",
        "",
        f"/* Snapshot DID  : {did.did_hex}",
        f" * ShortName    : {short_name}",
        f" * Size         : {did.size_bytes} bytes",
        f" * Product Type : {did.product_type}",
        f" * Record Nos   : {', '.join(record_numbers)}",
        " */",
        "",
        f"Std_ReturnType {did.read_fnc}(uint8* Data)",
        "{",
        f"    UBYTE {left_name};",
        f"    UBYTE {right_name};",
        "",
        f"    RcvMESG({left_name}, {items[0]});",
        f"    RcvMESG({right_name}, {items[1]});",
        "",
        f"    Data[0] = (uint8)({left_name} | ({right_name} << 4));",
        "",
        "    return E_OK;",
        "}",
        "",
    ])


def _guess_pattern(name: str) -> str:
    lower = name.lower()
    if any(k in lower for k in ("wheel speed", "vehicle speed", "speed")):
        return "RAM / internal interface (MESG struct, big-endian 16-bit values)"
    if any(k in lower for k in ("battery", "voltage", "power supply")):
        return "RAM / internal getter (direct function call + scaling)"
    if any(k in lower for k in ("avh", "apb", "epb", "autohold", "actuator")):
        return "RAM / internal interface (RBMESG, PbcOut or NMSG signals)"
    if any(k in lower for k in ("time", "year", "month", "day", "hour", "min", "sec")):
        return "RAM / internal interface (scalar NMSG time signals via RcvMESG)"
    if any(k in lower for k in ("sensor", "yaw", "acceleration", "pressure", "steering")):
        return "RAM / internal interface (MESG struct with qualifier check)"
    if any(k in lower for k in ("status", "state", "flag")):
        return "RAM / internal interface (bit-packed status byte(s))"
    return "RAM / internal interface (pattern undetermined; inspect project signals)"


def _render_sub_fields(did: SnapshotDIDInfo) -> List[str]:
    lines: List[str] = []
    for sf in did.sub_fields:
        if not any(sf.get(k) for k in ("name_en", "byte", "resolution", "range_min", "range_max", "unit")):
            continue
        if not sf.get("name_en") and not sf.get("byte"):
            continue
        name = sf.get("name_en", "") or "<unnamed field>"
        rng = f"[{sf.get('range_min', '')} ~ {sf.get('range_max', '')} {sf.get('unit', '').strip()}]".strip()
        res = sf.get("resolution", "")
        byte = sf.get("byte", "")
        prefix = f"Byte {byte} : " if byte else ""
        payload = f"{name} {rng}, res={res}".rstrip().rstrip(",")
        lines.append(f"{prefix}{payload}".rstrip())
    if not lines:
        lines.append("No structured sub-field data available.")
    return lines


def _render_pattern_hint_lines(name: str) -> List[str]:
    lower = name.lower()
    if any(k in lower for k in ("wheel speed", "vehicle speed", "speed")):
        return [
            "Use MESG struct macros (DefineMESGDef / RcvMESGDef) for speed signals.",
            "Check the Qualifier_N state before copying each 16-bit value.",
            "Copy to Data[] in big-endian order: upper byte first, lower byte second.",
            "Write 0xFF to both bytes when the source signal is invalid.",
        ]
    if any(k in lower for k in ("battery", "voltage", "power supply")):
        return [
            "Use a direct internal getter function for the physical value.",
            "Apply the project-specific scaling before casting to uint8.",
            "Write the final scaled byte(s) directly into Data[].",
        ]
    if any(k in lower for k in ("avh", "apb", "epb", "autohold", "actuator")):
        return [
            "Use RBMESG / NMSG receives or direct diagnostic output structs.",
            "For packed states, combine individual bits or nibbles into one output byte.",
            "Preserve explicit casts when shifting or packing sub-values.",
        ]
    if any(k in lower for k in ("time", "year", "month", "day", "hour", "min", "sec")):
        return [
            "Use scalar signal receives (for example via RcvMESG on time signals).",
            "Copy each time component directly to its assigned Data[] byte.",
        ]
    if any(k in lower for k in ("sensor", "yaw", "acceleration", "pressure", "steering")):
        return [
            "Use MESG struct receives with qualifier checks for each sensor source.",
            "Apply offset / scaling and then split multi-byte values in big-endian order.",
            "Write 0xFF bytes when the source qualifier marks the signal invalid.",
        ]
    if any(k in lower for k in ("status", "state", "flag")):
        return [
            "Build the output from boolean or enum inputs into packed status bytes.",
            "Use explicit masks and shifts for every packed field.",
        ]
    return [
        "Inspect the available internal interfaces and choose the correct MESG, RBMESG or direct getter source.",
        "Fill Data[] explicitly, preserving byte order and invalid-value handling.",
    ]
