"""Unit tests for the v2 (per-DID two-row) DOORS payload pipeline.

Covers:

* :mod:`scripts.fscs.doors.fscs_split` -- parse a renderer-produced
  FSCS_22.txt / FSCS_2E.txt string into per-DID heading/body blocks
  with the banner stripped.
* :mod:`scripts.fscs.doors.anchor` -- locate per-service anchor rows
  by exact and whitespace-normalised text match plus ``by_absolute_number``
  override.
* :mod:`scripts.fscs.doors.build_doors_payload` -- build the two
  per-service workbooks from a synthetic FSCS pair, validate the
  per-DID two-row layout (FS row carries Object Heading; CS row carries
  Object Text), and confirm the ``Common`` RB_Product semantics fan
  the cell out to every value-mapped product.
* :mod:`scripts.fscs.doors.doors_links` -- pair FS rows with the row
  that follows them (CS) by Object Heading match, and render a link
  xlsx whose source/target columns route CS -> FS by default.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from fscs.doors import anchor as anchor_mod
from fscs.doors import build_doors_payload as bdp
from fscs.doors import doors_links as links_mod
from fscs.doors import fscs_split


# --------------------------------------------------------------------- #
# fscs_split                                                            #
# --------------------------------------------------------------------- #


SAMPLE_FSCS = """\
# ==============================================================================
# Generated from outputs/fscs/fscs.json -- do not edit this file by hand.
# ==============================================================================

Identifier $5001h - Vehicle mode

Description
This identifier returns the Vehicle mode

Data Type:\tIdentity

================================================================================

Identifier $0301h - End Of Line Test Status

Description
This identifier returns the End Of Line Test Status

================================================================================
"""


def test_fscs_split_parses_two_blocks_with_banner_stripped():
    blocks = fscs_split.split_text(SAMPLE_FSCS)
    assert [b.did_hex for b in blocks] == ["0x5001", "0x0301"]
    assert blocks[0].did_name == "Vehicle mode"
    assert blocks[0].heading == "Identifier $5001h - Vehicle mode"
    assert blocks[0].body.startswith("Description")
    assert "Data Type:" in blocks[0].body
    assert blocks[1].did_name == "End Of Line Test Status"


def test_fscs_split_pads_short_hex_and_uppercases():
    txt = "Identifier $f1h - Tiny\n\nbody only\n"
    blocks = fscs_split.split_text(txt)
    assert len(blocks) == 1
    assert blocks[0].did_hex == "0x00F1"


def test_fscs_split_skips_blank_separator_chunks():
    txt = SAMPLE_FSCS + "\n=================\n\n\n"  # trailing separator + blanks
    blocks = fscs_split.split_text(txt)
    assert [b.did_hex for b in blocks] == ["0x5001", "0x0301"]


# --------------------------------------------------------------------- #
# anchor                                                                #
# --------------------------------------------------------------------- #


SAMPLE_EXPORT_ROWS = [
    {"AbsoluteNumber": "100", "DescriptionOfRequirementRB": "intro"},
    {
        "AbsoluteNumber": "401",
        "DescriptionOfRequirementRB": (
            "The ReadDataByIdentifier service allows the tester to request "
            "data record values from the ECU identified by one dataIdentifier.\n"
            "Mainstream configuration should be used."
        ),
    },
    {"AbsoluteNumber": "500", "DescriptionOfRequirementRB": "filler"},
    {
        "AbsoluteNumber": "999",
        "DescriptionOfRequirementRB": (
            "This service allows the Diagnosis tool to write data records "
            "into the ECU identified by Record Data Identifiers. The client "
            "request message contains 2-byte Data Identifier and the Data "
            "Record to be written into Servers memory.\n"
            "Mainstream configuration should be used."
        ),
    },
]


def test_anchor_resolves_by_text_verbatim():
    cfg = {
        "service_22": {
            "heading_field": "DescriptionOfRequirementRB",
            "text": SAMPLE_EXPORT_ROWS[1]["DescriptionOfRequirementRB"],
        },
        "service_2e": {
            "heading_field": "DescriptionOfRequirementRB",
            "text": SAMPLE_EXPORT_ROWS[3]["DescriptionOfRequirementRB"],
        },
    }
    result = anchor_mod.resolve_anchors(SAMPLE_EXPORT_ROWS, cfg)
    assert result["22"].anchor_address == "401"
    assert result["22"].rule == "by_text"
    assert result["2E"].anchor_address == "999"


def test_anchor_falls_back_to_normalised_match_when_whitespace_drifts():
    cfg = {
        "service_22": {
            "text": (
                "  The ReadDataByIdentifier service allows the tester to "
                "request data record values from the ECU identified by "
                "one dataIdentifier. Mainstream configuration should be used.  "
            ),
        },
        "service_2e": {
            "text": SAMPLE_EXPORT_ROWS[3]["DescriptionOfRequirementRB"],
        },
    }
    result = anchor_mod.resolve_anchors(SAMPLE_EXPORT_ROWS, cfg)
    assert result["22"].anchor_address == "401"
    assert result["22"].rule == "by_text+normalized"


def test_anchor_by_absolute_number_overrides_text_lookup():
    cfg = {
        "service_22": {"by_absolute_number": "777", "text": "irrelevant"},
        "service_2e": {"by_absolute_number": "888", "text": "irrelevant"},
    }
    result = anchor_mod.resolve_anchors(SAMPLE_EXPORT_ROWS, cfg)
    assert result["22"].anchor_address == "777"
    assert result["22"].rule == "by_absolute_number"
    assert result["22"].raw_row is None


def test_anchor_load_export_supports_data_rows_and_top_level_rows(tmp_path):
    nested = tmp_path / "nested.json"
    nested.write_text(
        json.dumps({"code": 0, "message": "OK", "data": {"rows": SAMPLE_EXPORT_ROWS}}),
        encoding="utf-8",
    )
    flat = tmp_path / "flat.json"
    flat.write_text(json.dumps({"rows": SAMPLE_EXPORT_ROWS}), encoding="utf-8")
    assert len(anchor_mod.load_export(nested)) == 4
    assert len(anchor_mod.load_export(flat)) == 4


def test_anchor_missing_text_raises_lookup_error():
    cfg = {
        "service_22": {"text": "this string is not in the export"},
        "service_2e": {"by_absolute_number": "888"},
    }
    with pytest.raises(LookupError):
        anchor_mod.resolve_anchors(SAMPLE_EXPORT_ROWS, cfg)


# --------------------------------------------------------------------- #
# build_doors_payload                                                   #
# --------------------------------------------------------------------- #


def _write_minimal_yaml(path: Path, *, rb_product_overrides: dict | None = None,
                        product_token: str | None = None) -> None:
    """v1.16.0 minimal YAML: 17-col template-aligned defaults, FS/CS
    role-aware values, basename-only realizing templates."""
    overrides = ""
    if rb_product_overrides:
        overrides = "rb_product_overrides:\n"
        for k, v in rb_product_overrides.items():
            overrides += f"  '{k}': '{v}'\n"
    path.write_text(
        f"""
doors:
  document_uuid: "demo-module"
anchors:
  service_22:
    heading_field: "DescriptionOfRequirementRB"
    text: |-
      ${product_token or '22 anchor text'}
  service_2e:
    heading_field: "DescriptionOfRequirementRB"
    text: |-
      $2E anchor text
template:
  sheet: "CS Data"
  size_row: 1
  header_row: 2
  data_start: 3
defaults:
  isPicture: "no"
role_values:
  FS:
    RB_Referenced_Testcase: "SwT"
    RB_TestEnvironment: "Labcar/HIL"
  CS:
    RB_Referenced_Testcase: "CT"
    RB_TestEnvironment: "SIL Simulation"
value_maps:
  RB_Product:
    DPB: "DPB"
    ESP: "ESP 10"
{overrides}
realizing_paths:
  fs_template: "Dcm_CusDiag_Services_EcucValues_{{product_type}}.arxml"
  cs_template: "RBAPLCUST_{{did_hex_bare}}_{{did_name}}.c"
  customer_default: "rbcn"
columns:
  "Destination Object":  "row.destination"
  "Absolute Number":     "row.absolute_no"
  "Object Heading":      "row.heading"
  "Object Text":         "row.object_text"
  "RB_Realizing_SWitem": "row.realizing"
  "RB_Product":          "row.rb_product"
  "isPicture":           "literal:no"
upload:
  init_timeout: 1
  upload_timeout: 1
""".lstrip(),
        encoding="utf-8",
    )


def _write_project(path: Path) -> None:
    """v1.16.0: project.json no longer carries product_type. Operator
    workflows pin it via the Phase 1/2/3 ``--product-type`` CLI flag
    or the per-DID ``Product_Type`` CSV column."""
    path.write_text(
        json.dumps({"project": {"name": "Demo"}}),
        encoding="utf-8",
    )


def _write_fscs_json(path: Path, *, did_product_types: dict[str, str]) -> None:
    """Write a tiny fscs.json for the DOORS payload to consume.

    v1.16.0: ``RB_Product`` is sourced PER DID from
    ``fscs.json::dids[].product_type`` rather than from
    ``project.product_type``. Tests build a tiny JSON that maps
    ``did_hex (with 0x prefix)`` to its product_type token.
    """
    payload = {
        "schema_version": "1.5",
        "dids": [
            # The DOORS payload reader only cares about did_hex +
            # product_type, so keep the rest of the entry minimal.
            {"did_hex": did_hex.removeprefix("0x").upper(),
             "product_type": product_type}
            for did_hex, product_type in did_product_types.items()
        ],
    }
    path.write_text(json.dumps(payload), encoding="utf-8")


def _read_workbook(path: Path):
    openpyxl = pytest.importorskip("openpyxl")
    wb = openpyxl.load_workbook(path)
    ws = wb.active
    rows = []
    headers = [c.value for c in ws[2]]
    for r in ws.iter_rows(min_row=3, values_only=True):
        rows.append(dict(zip(headers, r)))
    return headers, rows


@pytest.fixture
def synthetic_pair(tmp_path: Path) -> dict:
    txt22 = tmp_path / "FSCS_22.txt"
    txt2e = tmp_path / "FSCS_2E.txt"
    txt22.write_text(
        "Identifier $5001h - Vehicle mode\n\n"
        "Description\nbody for 5001\n"
        "================================================================================\n\n"
        "Identifier $0101h - Variant Coding\n\n"
        "Description\nbody for 0101\n",
        encoding="utf-8",
    )
    txt2e.write_text(
        "Identifier $0101h - Variant Coding\n\n"
        "Description\nwrite body\n",
        encoding="utf-8",
    )
    mapping = tmp_path / "doors_mapping.yaml"
    project = tmp_path / "project.json"
    fscs_json = tmp_path / "fscs.json"
    out_dir = tmp_path / "out"
    report = out_dir / "report.txt"
    return {
        "txt22": txt22, "txt2e": txt2e,
        "mapping": mapping, "project": project,
        "fscs_json": fscs_json,
        "out_dir": out_dir, "report": report,
    }


def test_build_payload_writes_two_xlsx_with_per_did_two_rows(synthetic_pair):
    pytest.importorskip("xlsxwriter")
    pytest.importorskip("yaml")
    pytest.importorskip("openpyxl")

    _write_minimal_yaml(synthetic_pair["mapping"])
    _write_project(synthetic_pair["project"])
    _write_fscs_json(
        synthetic_pair["fscs_json"],
        did_product_types={"0x5001": "DPB", "0x0101": "DPB"},
    )

    result = bdp.build_payload(
        mapping_path=synthetic_pair["mapping"],
        project_path=synthetic_pair["project"],
        export_path=Path("/does/not/exist"),
        txt_22_path=synthetic_pair["txt22"],
        txt_2e_path=synthetic_pair["txt2e"],
        fscs_json_path=synthetic_pair["fscs_json"],
        out_dir=synthetic_pair["out_dir"],
        report_path=synthetic_pair["report"],
        require_anchors=False,
    )

    art_22 = result.services["22"]
    art_2e = result.services["2E"]
    assert art_22.rows_written == 4   # 2 DIDs * 2 rows each
    assert art_2e.rows_written == 2   # 1 DID  * 2 rows each
    assert art_22.xlsx_path.is_file()
    assert art_2e.xlsx_path.is_file()
    assert art_22.did_hexes == ["0x5001", "0x0101"]

    headers, rows = _read_workbook(art_22.xlsx_path)
    assert "Object Heading" in headers and "Object Text" in headers
    fs_row = rows[0]
    cs_row = rows[1]
    assert fs_row["Object Heading"] == "Identifier $5001h - Vehicle mode"
    assert (cs_row["Object Heading"] is None) or (cs_row["Object Heading"] == "")
    assert (fs_row["Object Text"] is None) or (fs_row["Object Text"] == "")
    assert "body for 5001" in cs_row["Object Text"]
    assert fs_row["RB_Product"] == "DPB"
    assert cs_row["RB_Product"] == "DPB"


def test_build_payload_common_fans_out_rb_product(synthetic_pair):
    """v1.16.0: ``Common`` is now a *per-DID* token (read from
    ``fscs.json::dids[].product_type``), and the cell expands to
    every value in the ``value_maps.RB_Product`` mapping."""
    pytest.importorskip("xlsxwriter")
    pytest.importorskip("yaml")
    pytest.importorskip("openpyxl")

    _write_minimal_yaml(synthetic_pair["mapping"])
    _write_project(synthetic_pair["project"])
    _write_fscs_json(
        synthetic_pair["fscs_json"],
        did_product_types={"0x5001": "Common", "0x0101": "Common"},
    )

    result = bdp.build_payload(
        mapping_path=synthetic_pair["mapping"],
        project_path=synthetic_pair["project"],
        export_path=Path("/does/not/exist"),
        txt_22_path=synthetic_pair["txt22"],
        txt_2e_path=synthetic_pair["txt2e"],
        fscs_json_path=synthetic_pair["fscs_json"],
        out_dir=synthetic_pair["out_dir"],
        report_path=synthetic_pair["report"],
        require_anchors=False,
    )

    headers, rows = _read_workbook(result.services["22"].xlsx_path)
    assert rows[0]["RB_Product"] == "DPB\nESP 10"
    assert rows[1]["RB_Product"] == "DPB\nESP 10"


def test_build_payload_per_did_override_overrides_per_did_product_type(synthetic_pair):
    """v1.16.0 rename: the precedence is now
    ``rb_product_overrides[hex]`` (yaml) > ``dids[].product_type``
    (fscs.json) > empty cell. The ``project.product_type`` config
    knob no longer participates."""
    pytest.importorskip("xlsxwriter")
    pytest.importorskip("yaml")
    pytest.importorskip("openpyxl")

    _write_minimal_yaml(
        synthetic_pair["mapping"],
        rb_product_overrides={"0x0101": "Common"},
    )
    _write_project(synthetic_pair["project"])
    _write_fscs_json(
        synthetic_pair["fscs_json"],
        did_product_types={"0x5001": "DPB", "0x0101": "DPB"},
    )

    result = bdp.build_payload(
        mapping_path=synthetic_pair["mapping"],
        project_path=synthetic_pair["project"],
        export_path=Path("/does/not/exist"),
        txt_22_path=synthetic_pair["txt22"],
        txt_2e_path=synthetic_pair["txt2e"],
        fscs_json_path=synthetic_pair["fscs_json"],
        out_dir=synthetic_pair["out_dir"],
        report_path=synthetic_pair["report"],
        require_anchors=False,
    )

    headers, rows = _read_workbook(result.services["22"].xlsx_path)
    assert rows[0]["RB_Product"] == "DPB"            # 0x5001 (no override -> per-DID DPB)
    assert rows[2]["RB_Product"] == "DPB\nESP 10"    # 0x0101 (override Common)


def test_build_payload_reads_anchor_when_export_provided(synthetic_pair, tmp_path):
    pytest.importorskip("xlsxwriter")
    pytest.importorskip("yaml")
    pytest.importorskip("openpyxl")

    _write_minimal_yaml(synthetic_pair["mapping"])
    _write_project(synthetic_pair["project"])
    _write_fscs_json(
        synthetic_pair["fscs_json"],
        did_product_types={"0x5001": "DPB", "0x0101": "DPB"},
    )

    export_path = tmp_path / "doors_export.json"
    export_payload = {
        "code": 0, "message": "OK",
        "data": {"rows": [
            {"AbsoluteNumber": "401", "DescriptionOfRequirementRB": "$22 anchor text"},
            {"AbsoluteNumber": "999", "DescriptionOfRequirementRB": "$2E anchor text"},
        ]}
    }
    export_path.write_text(json.dumps(export_payload), encoding="utf-8")

    result = bdp.build_payload(
        mapping_path=synthetic_pair["mapping"],
        project_path=synthetic_pair["project"],
        export_path=export_path,
        txt_22_path=synthetic_pair["txt22"],
        txt_2e_path=synthetic_pair["txt2e"],
        fscs_json_path=synthetic_pair["fscs_json"],
        out_dir=synthetic_pair["out_dir"],
        report_path=synthetic_pair["report"],
        require_anchors=True,
    )
    assert result.services["22"].anchor.anchor_address == "401"
    assert result.services["2E"].anchor.anchor_address == "999"
    headers, rows = _read_workbook(result.services["22"].xlsx_path)
    assert rows[0]["Destination Object"] == "401"
    assert rows[1]["Destination Object"] == "401"   # CS row carries the anchor too


def test_build_payload_realizing_basenames_per_role(synthetic_pair):
    """v1.16.0: RB_Realizing_SWitem is FILENAME ONLY, FS=.arxml,
    CS=.c. Path-shaped templates are reduced to their basename so
    legacy mappings keep working without manual edits."""
    pytest.importorskip("xlsxwriter")
    pytest.importorskip("yaml")
    pytest.importorskip("openpyxl")

    _write_minimal_yaml(synthetic_pair["mapping"])
    _write_project(synthetic_pair["project"])
    _write_fscs_json(
        synthetic_pair["fscs_json"],
        did_product_types={"0x5001": "DPB", "0x0101": "DPB"},
    )

    result = bdp.build_payload(
        mapping_path=synthetic_pair["mapping"],
        project_path=synthetic_pair["project"],
        export_path=Path("/does/not/exist"),
        txt_22_path=synthetic_pair["txt22"],
        txt_2e_path=synthetic_pair["txt2e"],
        fscs_json_path=synthetic_pair["fscs_json"],
        out_dir=synthetic_pair["out_dir"],
        report_path=synthetic_pair["report"],
        require_anchors=False,
    )

    headers, rows = _read_workbook(result.services["22"].xlsx_path)
    fs_row = rows[0]   # 0x5001 FS
    cs_row = rows[1]   # 0x5001 CS
    # FS row gets the .arxml basename (no path prefix).
    assert fs_row["RB_Realizing_SWitem"] == "Dcm_CusDiag_Services_EcucValues_DPB.arxml"
    assert "/" not in fs_row["RB_Realizing_SWitem"]
    assert "\\" not in fs_row["RB_Realizing_SWitem"]
    # CS row gets the .c basename.
    assert cs_row["RB_Realizing_SWitem"] == "RBAPLCUST_5001_Vehicle_mode.c"


def test_build_payload_object_text_carries_full_behavior(synthetic_pair):
    """v1.16.0 regression pin: the CS row's Object Text must carry
    the FULL DID body (every line after the heading), including the
    multi-line Behavior section. Truncating the Behavior section
    drops the operator's diag spec from DOORS, so this is a hard
    integrity guarantee."""
    pytest.importorskip("xlsxwriter")
    pytest.importorskip("yaml")
    pytest.importorskip("openpyxl")

    # Synthetic FSCS that mirrors the real renderer layout: a
    # multi-line Behavior section with a header, a `interface:`
    # marker, and an indented body. If ANY of those lines goes
    # missing in Object Text, the assertion below fires.
    txt22 = synthetic_pair["txt22"]
    txt22.write_text(
        "Identifier $5001h - Vehicle mode\n\n"
        "Description\n"
        "This identifier returns the Vehicle mode.\n"
        "\n"
        "Data Type:\tIdentity\n"
        "\n"
        "Behavior:\n"
        "interface:\n"
        "  step 1: read DCOM_VehicleMode\n"
        "  step 2: convert to UDS scale\n"
        "  step 3: return\n",
        encoding="utf-8",
    )

    _write_minimal_yaml(synthetic_pair["mapping"])
    _write_project(synthetic_pair["project"])
    _write_fscs_json(
        synthetic_pair["fscs_json"],
        did_product_types={"0x5001": "DPB"},
    )

    result = bdp.build_payload(
        mapping_path=synthetic_pair["mapping"],
        project_path=synthetic_pair["project"],
        export_path=Path("/does/not/exist"),
        txt_22_path=txt22,
        txt_2e_path=synthetic_pair["txt2e"],
        fscs_json_path=synthetic_pair["fscs_json"],
        out_dir=synthetic_pair["out_dir"],
        report_path=synthetic_pair["report"],
        require_anchors=False,
    )

    _, rows = _read_workbook(result.services["22"].xlsx_path)
    cs_row = rows[1]
    text = cs_row["Object Text"] or ""
    # Every distinguishing line of the body must survive verbatim.
    for needle in (
        "Description",
        "This identifier returns the Vehicle mode.",
        "Data Type:",
        "Behavior:",
        "interface:",
        "step 1: read DCOM_VehicleMode",
        "step 3: return",
    ):
        assert needle in text, (
            f"Object Text dropped {needle!r}; CS row truncates the "
            f"Behavior section — full text was:\n{text!r}"
        )


# --------------------------------------------------------------------- #
# doors_links                                                           #
# --------------------------------------------------------------------- #


def test_reconcile_pairs_fs_with_following_cs_row():
    rows = [
        {"AbsoluteNumber": "200", "DescriptionOfRequirementRB": "Identifier $5001h - Vehicle mode"},
        {"AbsoluteNumber": "201", "DescriptionOfRequirementRB": "<body of 5001>"},
        {"AbsoluteNumber": "202", "DescriptionOfRequirementRB": "Identifier $0101h - Variant Coding"},
        {"AbsoluteNumber": "203", "DescriptionOfRequirementRB": "<body of 0101>"},
    ]
    did_to_heading = {
        "0x5001": "Identifier $5001h - Vehicle mode",
        "0x0101": "Identifier $0101h - Variant Coding",
    }
    pairs = links_mod.reconcile_did_rows(rows=rows, did_hex_to_heading=did_to_heading)
    assert [(p.did_hex, p.fs_abs, p.cs_abs) for p in pairs] == [
        ("0x5001", "200", "201"),
        ("0x0101", "202", "203"),
    ]


def test_reconcile_skips_unmatched_dids():
    rows = [
        {"AbsoluteNumber": "200", "DescriptionOfRequirementRB": "Identifier $5001h - Vehicle mode"},
        {"AbsoluteNumber": "201", "DescriptionOfRequirementRB": "<body of 5001>"},
    ]
    pairs = links_mod.reconcile_did_rows(
        rows=rows,
        did_hex_to_heading={"0x9999": "Identifier $9999h - Missing"},
    )
    assert pairs == []


def test_reconcile_with_service_ranges_tags_each_match_per_service():
    """v1.17.1: when the caller supplies ``service_ranges`` (built
    from the fresh export's resolved anchor positions), every
    matched DID×service pair gets its OWN ``LinkEntry`` carrying
    the correct ``service`` tag and the per-anchor AbsoluteNumbers.

    The fixture below mirrors a real DOORS module: one $22 anchor
    block then one $2E anchor block, with the SAME DID (0x0101)
    landing in BOTH services at physically distinct row pairs.
    Without service_ranges, only one (fs_abs, cs_abs) pair would
    be returned for that DID and the writeback would mis-record;
    with service_ranges we get both.
    """
    rows = [
        # idx 0: 22 service anchor row
        {"AbsoluteNumber": "100", "DescriptionOfRequirementRB": "$22 anchor"},
        # idx 1-4: 22 service content (one DID-pair per service)
        {"AbsoluteNumber": "200", "DescriptionOfRequirementRB": "Identifier $5001h - Vehicle mode"},
        {"AbsoluteNumber": "201", "DescriptionOfRequirementRB": "<body of 5001 in 22>"},
        {"AbsoluteNumber": "202", "DescriptionOfRequirementRB": "Identifier $0101h - Variant Coding"},
        {"AbsoluteNumber": "203", "DescriptionOfRequirementRB": "<body of 0101 in 22>"},
        # idx 5: 2E service anchor row
        {"AbsoluteNumber": "300", "DescriptionOfRequirementRB": "$2E anchor"},
        # idx 6-7: 2E service content (only 0x0101 lives in 2E)
        {"AbsoluteNumber": "400", "DescriptionOfRequirementRB": "Identifier $0101h - Variant Coding"},
        {"AbsoluteNumber": "401", "DescriptionOfRequirementRB": "<body of 0101 in 2E>"},
    ]
    did_to_heading = {
        "0x5001": "Identifier $5001h - Vehicle mode",
        "0x0101": "Identifier $0101h - Variant Coding",
    }
    # Anchor at idx 0 -> 22 block is rows [1..5); anchor at idx 5
    # -> 2E block is rows [6..8).
    service_ranges = {"22": (1, 5), "2E": (6, 8)}
    pairs = links_mod.reconcile_did_rows(
        rows=rows,
        did_hex_to_heading=did_to_heading,
        service_ranges=service_ranges,
    )
    triples = [(p.did_hex, p.service, p.fs_abs, p.cs_abs) for p in pairs]
    assert triples == [
        ("0x5001", "22", "200", "201"),
        ("0x0101", "22", "202", "203"),
        # CRITICAL: 0x0101 produces a SECOND entry with the 2E
        # block's distinct AbsoluteNumbers, not a duplicate of
        # the 22 entry.
        ("0x0101", "2E", "400", "401"),
    ]


def test_reconcile_without_service_ranges_keeps_v1_16_unannotated_form():
    """Backward-compat: callers that don't supply ``service_ranges``
    still get the v1.16.0 behaviour — one entry per match with
    ``service=""``. The orchestrator's ``_annotate_service``
    fallback then patches up the service field via the
    per-service DID lists."""
    rows = [
        {"AbsoluteNumber": "200", "DescriptionOfRequirementRB": "Identifier $5001h - Vehicle mode"},
        {"AbsoluteNumber": "201", "DescriptionOfRequirementRB": "<body of 5001>"},
    ]
    pairs = links_mod.reconcile_did_rows(
        rows=rows,
        did_hex_to_heading={"0x5001": "Identifier $5001h - Vehicle mode"},
    )
    assert len(pairs) == 1
    assert pairs[0].service == ""


def test_build_link_xlsx_writes_six_columns(tmp_path):
    pytest.importorskip("xlsxwriter")
    pytest.importorskip("openpyxl")
    out = tmp_path / "links.xlsx"
    n = links_mod.build_link_xlsx(
        out_path=out,
        entries=[
            links_mod.LinkEntry(cs_abs="201", fs_abs="200", did_hex="0x5001", service="22"),
            links_mod.LinkEntry(cs_abs="203", fs_abs="202", did_hex="0x0101", service="22+2E"),
        ],
        source_module_uuid="MOD-A",
        target_module_uuid="MOD-A",
        link_type="Realisation",
        link_module_uuid="LINK-MOD",
    )
    assert n == 2
    import openpyxl  # noqa: F401  (already imported via importorskip)
    from openpyxl import load_workbook
    wb = load_workbook(out)
    ws = wb.active
    headers = [c.value for c in ws[2]]
    assert headers == [
        "Source Module", "Source AbsoluteNumber",
        "Target Module", "Target AbsoluteNumber",
        "Link Type", "Link Module",
    ]
    first = dict(zip(headers, [c.value for c in ws[3]]))
    assert first["Source AbsoluteNumber"] == "201"   # CS row
    assert first["Target AbsoluteNumber"] == "200"   # FS row
    assert first["Link Type"] == "Realisation"
    assert first["Link Module"] == "LINK-MOD"


def test_build_link_xlsx_direction_fs_to_cs_swaps_columns(tmp_path):
    pytest.importorskip("xlsxwriter")
    pytest.importorskip("openpyxl")
    out = tmp_path / "links.xlsx"
    links_mod.build_link_xlsx(
        out_path=out,
        entries=[links_mod.LinkEntry(cs_abs="201", fs_abs="200", did_hex="0x5001", service="22")],
        source_module_uuid="MOD-A",
        target_module_uuid="MOD-A",
        link_type="Realisation",
        link_module_uuid="LINK-MOD",
        direction="fs_to_cs",
    )
    from openpyxl import load_workbook
    wb = load_workbook(out)
    ws = wb.active
    headers = [c.value for c in ws[2]]
    first = dict(zip(headers, [c.value for c in ws[3]]))
    assert first["Source AbsoluteNumber"] == "200"   # FS now source
    assert first["Target AbsoluteNumber"] == "201"   # CS now target


# --------------------------------------------------------------------- #
# v1.17.0 state machine -- INSERT / UPDATE / NOOP / STALE coverage      #
# --------------------------------------------------------------------- #
#
# These four scenarios pin the workbook-side semantics of the new
# state machine: empty state -> all INSERT, fully-stale state ->
# all UPDATE, mixed -> only changed rows land, and all-NOOP ->
# empty workbook (still on disk so the orchestrator's path
# reporting stays consistent). Together with
# ``test_doors_diff.py`` they cover both ends of the plan
# protocol, so a regression in either layer surfaces fast.

from fscs.doors.doors_state import (  # noqa: E402  (test-section local)
    DIDState,
    ModuleState,
    ServiceLanding,
    State,
    now_utc_iso,
)


_MODULE_UUID = "demo-module"  # matches doors.document_uuid in _write_minimal_yaml


def _write_state_machine_pair(synthetic_pair: dict) -> None:
    """Common fixture wiring used by every state-machine scenario:
    minimal yaml + project + fscs.json with both DIDs tagged DPB.

    Kept tiny and explicit so each scenario's assertion block reads
    independently of the others (no shared setup hidden behind a
    fixture wrapper)."""
    _write_minimal_yaml(synthetic_pair["mapping"])
    _write_project(synthetic_pair["project"])
    _write_fscs_json(
        synthetic_pair["fscs_json"],
        did_product_types={"0x5001": "DPB", "0x0101": "DPB"},
    )


def _build_with_state(
    synthetic_pair: dict,
    *,
    state: State | None,
    module_uuid: str | None,
):
    """Tiny wrapper around ``bdp.build_payload`` so each scenario only
    spells out the state plumbing it cares about. Skips
    ``require_anchors`` because the synthetic pair has no DOORS
    export."""
    return bdp.build_payload(
        mapping_path=synthetic_pair["mapping"],
        project_path=synthetic_pair["project"],
        export_path=Path("/does/not/exist"),
        txt_22_path=synthetic_pair["txt22"],
        txt_2e_path=synthetic_pair["txt2e"],
        fscs_json_path=synthetic_pair["fscs_json"],
        out_dir=synthetic_pair["out_dir"],
        report_path=synthetic_pair["report"],
        require_anchors=False,
        state=state,
        module_uuid=module_uuid,
    )


def _seed_state_for(
    *,
    pair_hashes: dict[tuple[str, str], str],
    module_uuid: str,
    fs_abs_template: str = "FS-{hex}-{svc}",
    cs_abs_template: str = "CS-{hex}-{svc}",
    overwrite_hash: dict[tuple[str, str], str] | None = None,
) -> State:
    """Build a synthetic State that records every (service, did_hex)
    in ``pair_hashes`` for ``module_uuid``.

    ``overwrite_hash`` lets a caller intentionally drift recorded
    hashes (UPDATE setup); pairs absent from it inherit the live
    hash so the diff classifies them as NOOP.
    """
    state = State()
    module = state.for_module(module_uuid)
    module.last_uploaded_at = now_utc_iso()
    overwrite_hash = overwrite_hash or {}
    for (service, did_hex), live_hash in pair_hashes.items():
        recorded_hash = overwrite_hash.get((service, did_hex), live_hash)
        landing = ServiceLanding(
            fs_abs=fs_abs_template.format(hex=did_hex, svc=service),
            cs_abs=cs_abs_template.format(hex=did_hex, svc=service),
            content_hash=recorded_hash,
            last_uploaded_at=now_utc_iso(),
        )
        module.remember(did_hex, service, landing)
    return state


def test_state_machine_pure_insert_writes_all_rows_destination_only(synthetic_pair):
    """First-ever push (empty state, fresh module): every effective
    DID×service must classify as INSERT, all FS+CS rows must land
    in the workbook, ``Destination Object`` carries the anchor (or
    the dry-run placeholder), and ``Absolute Number`` is blank.

    NB: ``RowCtx.mode`` is "insert" by default; this test pins
    that the cell-level mutations downstream actually do honour it.
    """
    pytest.importorskip("xlsxwriter")
    pytest.importorskip("yaml")
    pytest.importorskip("openpyxl")

    _write_state_machine_pair(synthetic_pair)
    state = State()  # empty -- no prior knowledge of any module

    result = _build_with_state(synthetic_pair, state=state, module_uuid=_MODULE_UUID)

    assert result.action_plan is not None
    summary = result.action_plan.summary()
    assert summary["INSERT"] == 3   # 22 has 2 DIDs, 2E has 1 DID
    assert summary["UPDATE"] == 0
    assert summary["NOOP"] == 0
    assert summary["STALE"] == 0

    art_22 = result.services["22"]
    art_2e = result.services["2E"]
    assert art_22.rows_written == 4   # 2 DIDs * 2 rows
    assert art_2e.rows_written == 2   # 1 DID  * 2 rows

    _, rows_22 = _read_workbook(art_22.xlsx_path)
    for row in rows_22:
        # Anchor placeholder lands as "" in dry-run mode -> Destination
        # Object is allowed to be blank, but the column must EXIST and
        # the Absolute Number column must be blank everywhere (INSERT).
        assert (row["Absolute Number"] is None) or (row["Absolute Number"] == "")


def test_state_machine_pure_update_writes_all_rows_with_absolute_number(synthetic_pair):
    """Every DID×service is recorded with a STALE (drifted) hash:
    the diff must classify all of them as UPDATE, the workbook
    keeps every FS+CS row, but now ``Absolute Number`` carries
    the recorded landings and ``Destination Object`` is blank
    so DOORS overwrites in place rather than re-appending."""
    pytest.importorskip("xlsxwriter")
    pytest.importorskip("yaml")
    pytest.importorskip("openpyxl")

    _write_state_machine_pair(synthetic_pair)

    # First-pass build with no state to harvest the live content
    # hashes -- we then deliberately corrupt them in the seeded
    # state so the second pass classifies everything as UPDATE.
    probe = _build_with_state(synthetic_pair, state=None, module_uuid=None)
    live_hashes = dict(probe.did_pair_hashes)
    assert live_hashes, "probe must have produced at least one pair hash"

    poisoned = "sha256:" + ("0" * 64)
    state = _seed_state_for(
        pair_hashes=live_hashes,
        module_uuid=_MODULE_UUID,
        overwrite_hash={k: poisoned for k in live_hashes},
    )

    result = _build_with_state(synthetic_pair, state=state, module_uuid=_MODULE_UUID)

    summary = result.action_plan.summary()
    assert summary["UPDATE"] == 3
    assert summary["INSERT"] == 0
    assert summary["NOOP"] == 0

    art_22 = result.services["22"]
    assert art_22.rows_written == 4   # UPDATE still emits FS+CS

    _, rows_22 = _read_workbook(art_22.xlsx_path)
    for row in rows_22:
        # UPDATE inverts the cell pair: Destination Object blank,
        # Absolute Number filled with the recorded landing.
        assert (row["Destination Object"] is None) or (row["Destination Object"] == "")
        assert row["Absolute Number"] not in (None, "")
        # Recorded values come from _seed_state_for's templates so
        # we can sanity-check the wiring end-to-end.
        assert row["Absolute Number"].startswith(("FS-0x", "CS-0x"))


def test_state_machine_mixed_insert_update_noop_skips_only_noop_rows(synthetic_pair):
    """The interesting middle case: one DID per bucket. The NOOP
    DID must not appear in the workbook at all (cheapest possible
    push), while INSERT and UPDATE still land FS+CS rows with
    their correct cell semantics."""
    pytest.importorskip("xlsxwriter")
    pytest.importorskip("yaml")
    pytest.importorskip("openpyxl")

    _write_state_machine_pair(synthetic_pair)

    probe = _build_with_state(synthetic_pair, state=None, module_uuid=None)
    live_hashes = dict(probe.did_pair_hashes)

    # 22 has two DIDs (5001, 0101), 2E has one (0101). Pin:
    #   ("22", "0x5001") -> NOOP  (recorded with matching hash)
    #   ("22", "0x0101") -> UPDATE (recorded with poisoned hash)
    #   ("2E", "0x0101") -> INSERT (NOT recorded at all)
    poisoned = "sha256:" + ("a" * 64)
    state = State()
    module = state.for_module(_MODULE_UUID)
    module.last_uploaded_at = now_utc_iso()
    module.remember(
        "0x5001", "22",
        ServiceLanding(
            fs_abs="ABS-NOOP-FS",
            cs_abs="ABS-NOOP-CS",
            content_hash=live_hashes[("22", "0x5001")],
            last_uploaded_at=now_utc_iso(),
        ),
    )
    module.remember(
        "0x0101", "22",
        ServiceLanding(
            fs_abs="ABS-UPDATE-FS",
            cs_abs="ABS-UPDATE-CS",
            content_hash=poisoned,
            last_uploaded_at=now_utc_iso(),
        ),
    )

    result = _build_with_state(synthetic_pair, state=state, module_uuid=_MODULE_UUID)

    summary = result.action_plan.summary()
    assert summary["NOOP"] == 1
    assert summary["UPDATE"] == 1
    assert summary["INSERT"] == 1
    assert summary["STALE"] == 0

    art_22 = result.services["22"]
    art_2e = result.services["2E"]
    # 22 sheet: NOOP (5001) skipped + UPDATE (0101) FS+CS = 2 rows
    assert art_22.rows_written == 2
    assert art_22.did_hexes == ["0x0101"]   # NOOP'd hex must NOT be listed
    # 2E sheet: INSERT (0101) FS+CS = 2 rows
    assert art_2e.rows_written == 2
    assert art_2e.did_hexes == ["0x0101"]

    _, rows_22 = _read_workbook(art_22.xlsx_path)
    # Every surviving 22 row is the UPDATE -> Absolute Number filled,
    # Destination Object blank.
    for row in rows_22:
        assert row["Absolute Number"] in ("ABS-UPDATE-FS", "ABS-UPDATE-CS")
        assert (row["Destination Object"] is None) or (row["Destination Object"] == "")

    _, rows_2e = _read_workbook(art_2e.xlsx_path)
    # The 2E row pair is an INSERT -> Absolute Number blank.
    for row in rows_2e:
        assert (row["Absolute Number"] is None) or (row["Absolute Number"] == "")


def test_state_machine_all_noop_writes_empty_workbook_with_zero_data_rows(synthetic_pair):
    """When the recorded hashes match every live hash we must NOT
    emit any FS/CS rows; the workbook is still written so the
    orchestrator's path-reporting and filesystem invariants stay
    consistent (downstream upload short-circuits on
    rows_written == 0)."""
    pytest.importorskip("xlsxwriter")
    pytest.importorskip("yaml")
    pytest.importorskip("openpyxl")

    _write_state_machine_pair(synthetic_pair)

    probe = _build_with_state(synthetic_pair, state=None, module_uuid=None)
    live_hashes = dict(probe.did_pair_hashes)

    state = _seed_state_for(
        pair_hashes=live_hashes,
        module_uuid=_MODULE_UUID,
    )

    result = _build_with_state(synthetic_pair, state=state, module_uuid=_MODULE_UUID)

    summary = result.action_plan.summary()
    assert summary["NOOP"] == 3
    assert summary["INSERT"] == 0
    assert summary["UPDATE"] == 0
    assert summary["STALE"] == 0

    for service in ("22", "2E"):
        art = result.services[service]
        assert art.rows_written == 0
        assert art.did_hexes == []
        assert art.xlsx_path.is_file(), (
            f"workbook must still be written for service {service} "
            "even when every DID is NOOP -- the orchestrator relies "
            "on the path existing for its reporting / archival step"
        )
