"""Phase 1: diagnostic questionnaire -> fscs.json + FSCS_19.txt."""

import json
import pathlib
import re
from typing import Any, Dict, List, Optional

from io_encoding import save_json, save_text
from xlsx_parser import parse_freeze_frame_sheet


def run_phase1(workspace: pathlib.Path, args: Any) -> int:
    config_path = workspace / "config" / "project.json"
    config = json.loads(config_path.read_text(encoding="utf-8"))
    xlsx_path = pathlib.Path(config["paths"]["input_xlsx"])
    if not xlsx_path.exists():
        print(f"[ERROR] Input xlsx not found: {xlsx_path}")
        return 1

    product_types = config.get("product_types", ["Common"])
    result = parse_freeze_frame_sheet(xlsx_path, product_types)

    out_dir = workspace / "outputs" / "fscs"
    out_dir.mkdir(parents=True, exist_ok=True)

    # Preserve operator-entered implementation notes across Phase 1 re-runs.
    existing_doc = _load_existing_fscs(out_dir / "fscs.json")
    if existing_doc is not None:
        _merge_impl_notes(existing_doc, result)

    save_json(out_dir / "fscs.json", result)
    save_text(out_dir / "FSCS_19.txt", _render_fscs_19(result))
    _write_review_report(out_dir / "fscs_review_report.txt", result)
    _write_xlsx_edit(out_dir / "fscs_edit.xlsx", result)

    print(f"[OK] Phase 1 complete. {len(result['dids'])} DIDs emitted.")
    print(f"[AGENT STOP] Review {out_dir / 'fscs_edit.xlsx'} then run --phase xlsx-import.")
    return 0


def _render_fscs_19(doc: Dict[str, Any]) -> str:
    lines = [
        "# Generated by 19service-toolkit -- do not edit by hand.",
        f"# Service: {doc['service']} Subfunction: {doc['subfunction']}",
        "",
        "Positive Response Message:",
        "Byte 1\t\t$59 = Response Service Id \"ReadDTCInformation\"",
        "",
        "Byte 2\t\tsubFunction = [reportType]",
        f"\t\t${doc['subfunction'][2:]} = reportDTCSnapshotRecordByDTCNumber",
        "",
        "Byte 3\t\tDTCHighByte",
        "Byte 4\t\tDTCMiddleByte",
        "Byte 5\t\tDTCLowByte",
        "Byte 6\t\tstatusOfDTC",
        "",
        "",
        "Byte 7\t\tDTCSnapshotRecordNumber",
    ]

    descriptions = doc.get("snapshot_record_number_descriptions", {})
    for rec in doc.get("dtc_snapshot_record_numbers", ["0x01", "0xFF"]):
        desc = descriptions.get(rec, "")
        lines.append(f"             ${rec[2:]}: {desc}" if desc else f"             ${rec[2:]}")

    effective_dids = [d for d in doc["dids"] if d.get("used", True)]
    lines.append(f"Byte 8\t\tDTCSnapshotRecordNumberOfIdentifiers = {len(effective_dids)}")
    lines.append("")
    lines.append("DTCSnapshotRecord ")

    byte_index = 9
    for idx, did in enumerate(effective_dids, start=1):
        did_msb, did_lsb = _split_did(did["did_hex"])
        lines.append(f"Byte {byte_index}\t\tDataIdentifier#{idx}: {did['did_name_en']} (MSB) = ${did_msb}")
        lines.append(f"Byte {byte_index+1}\t\tDataIdentifier#{idx}: {did['did_name_en']} (LSB) = ${did_lsb}")

        value_start = byte_index + 2
        value_end = value_start + did["size_bytes"] - 1
        if did["size_bytes"] == 1:
            lines.append(f"Byte {value_start}\t\t{did['did_name_en']} Value")
        else:
            lines.append(f"Byte {value_start}-{value_end}\t\t{did['did_name_en']} Value")

        # Resolution / Range from first meaningful sub-field
        sf = _first_meaningful_sub_field(did)
        if sf:
            unit = sf.get("unit", "").strip()
            resolution = sf.get("resolution", "").strip()
            if resolution:
                lines.append(f"\t\t Resolution: {resolution}{unit}")
            range_min = sf.get("range_min", "").strip()
            range_max = sf.get("range_max", "").strip()
            if range_min or range_max:
                lines.append(f"\t\t Range: {range_min} ~ {range_max}{unit}")
        else:
            lines.append(f"\t\t Size: {did['size_bytes']} bytes")
            lines.append(f"\t\t Read Function: {did.get('read_fnc', 'TBD')}")

        byte_index = value_end + 1

    # Template B
    lines.append("")
    lines.append("Available Snapshot Data")
    lines.append("")
    for did in effective_dids:
        lines.append(
            f"Function interfaces:{did.get('read_fnc', 'TBD')} will be used for snapshot data record configuration"
        )

    return "\n".join(lines)


def _load_existing_fscs(path: pathlib.Path) -> Optional[Dict[str, Any]]:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _merge_impl_notes(existing_doc: Dict[str, Any], new_doc: Dict[str, Any]) -> None:
    old_notes = {
        did.get("did_hex"): did.get("impl_notes", "")
        for did in existing_doc.get("dids", [])
        if did.get("did_hex")
    }
    for did in new_doc.get("dids", []):
        old_value = old_notes.get(did.get("did_hex"), "")
        if old_value:
            did["impl_notes"] = old_value


def _first_meaningful_sub_field(did: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    for sf in did.get("sub_fields", []):
        if sf.get("name_en") or sf.get("method_en") or sf.get("resolution"):
            return sf
    return None


def _split_did(did_hex: str) -> tuple:
    val = int(did_hex, 16)
    return f"{(val >> 8) & 0xFF:02X}", f"{val & 0xFF:02X}"


def _write_review_report(path: pathlib.Path, doc: Dict[str, Any]) -> None:
    lines = ["FSCS Review Report", "=" * 40, ""]
    lines.append(f"Service: {doc['service']} Subfunction: {doc['subfunction']}")
    lines.append(f"Freeze-frame class: {doc['freeze_frame_class']}")
    lines.append(f"DIDs: {len(doc['dids'])}")
    for did in doc["dids"]:
        lines.append(f"  {did['did_hex']} {did['did_name_en']} ({did['size_bytes']} bytes) PT={did.get('product_type','Common')} used={did.get('used',True)}")
    save_text(path, "\n".join(lines))


def _write_xlsx_edit(path: pathlib.Path, doc: Dict[str, Any]) -> None:
    try:
        import openpyxl
    except ImportError:  # pragma: no cover
        print("[WARN] openpyxl not installed; skipping fscs_edit.xlsx")
        return

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "FSCS_19"
    headers = ["used_flag", "Product_Type", "did_hex", "did_name_en", "did_name_zh",
               "size_bytes", "read_fnc", "subfunction", "record_number",
               "sub_field_byte", "sub_field_bit", "sub_field_name_en", "sub_field_name_zh",
               "range_min", "range_max", "unit", "resolution", "offset",
               "impl_notes"]
    ws.append(headers)

    record_numbers = ", ".join(doc.get("dtc_snapshot_record_numbers", []))
    for did in doc["dids"]:
        sub_fields = did.get("sub_fields", [])
        if not sub_fields:
            ws.append([
                "Y" if did.get("used", True) else "N",
                did.get("product_type", "Common"),
                did["did_hex"],
                did["did_name_en"],
                did.get("did_name_zh", ""),
                did["size_bytes"],
                did.get("read_fnc", ""),
                doc["subfunction"],
                record_numbers,
                "", "", "", "", "", "", "", "", "",
                did.get("impl_notes", ""),
            ])
        else:
            for idx, sf in enumerate(sub_fields):
                is_first = idx == 0
                ws.append([
                    "Y" if is_first and did.get("used", True) else ("N" if is_first else ""),
                    did.get("product_type", "Common") if is_first else "",
                    did["did_hex"] if is_first else "",
                    did["did_name_en"] if is_first else "",
                    did.get("did_name_zh", "") if is_first else "",
                    did["size_bytes"] if is_first else "",
                    did.get("read_fnc", "") if is_first else "",
                    doc["subfunction"] if is_first else "",
                    record_numbers if is_first else "",
                    sf.get("byte", ""),
                    sf.get("bit", ""),
                    sf.get("name_en", ""),
                    sf.get("name_zh", ""),
                    sf.get("range_min", ""),
                    sf.get("range_max", ""),
                    sf.get("unit", ""),
                    sf.get("resolution", ""),
                    sf.get("offset", ""),
                    did.get("impl_notes", "") if is_first else "",
                ])
    wb.save(path)
