#!/usr/bin/env python3
"""FSCS Document Generator -- Phase 1.

This module accepts ONLY schema-compliant ``*_did.json`` (see
``reference/input-format.md``). The skill ships no built-in
workbook parser, so any ``.xlsx`` questionnaire must first be
normalised into ``inputs/<customer>_did.json`` by an
operator/agent-written one-off
``.DCOM_AI/DID_Toolkit_PRJ/scripts/extract_<customer>.py`` adapter. Phase 1 is
strictly JSON-in, JSON-out; the skill keeps no customer-specific
extractor code so it stays a generic configuration toolkit.

Produces two coupled artefacts from one DID JSON input:

* ``outputs/fscs/fscs.json`` -- authoritative Phase 1 output consumed
  by Phase 2, Phase 3, every reviewer, and the xlsx edit workflow. This is
  the only file the downstream pipeline reads.
* ``outputs/fscs/fscs_generation_report.txt`` -- human-readable summary
  of *which* input records made it into ``fscs.json``, which were
  filtered out because ``supported_by_ecu != "Y"``, and which were
  skipped because they failed schema validation. Lets operators fix
  upstream data incrementally without the whole pipeline aborting on
  one bad row. This is the **ingestion** report; the content **audit**
  lives in ``fscs_review_report.txt`` -- see below.

**FSCS_22.txt / FSCS_2E.txt are not produced here.** This module is
strictly JSON-in, JSON-out. The two text views are generated by
``pipeline.py --phase xlsx-import`` after the operator edits
``fscs_edit.xlsx``; at that point the ``used`` selection has been curated
and it makes sense to persist the filtered text renderings.

**Business review is auto-invoked**, but orchestrated by
``pipeline.py::run_phase1`` rather than this module. The
generator's single responsibility stays "build ``fscs.json`` + the
ingestion report"; the pipeline layer chains the content review onto
the end (see ``pipeline.PipelineController._run_fscs_review``). Running
``generate_fscs.py`` directly therefore skips the review step -- that
script is the *low-level* builder. Use ``python scripts/pipeline.py
--phase fscs`` for the normal operator path (review included), or
``--no-review`` / ``DID_NO_REVIEW=1`` to explicitly opt out.

Two-gate persistence (``used`` flags):

* First run: every DID gets ``used_22 = used_2e = True``.
* Subsequent runs: operator selections made through the xlsx-import are
  preserved by reading the pre-existing ``fscs.json`` and copying the
  ``used_22`` / ``used_2e`` flags onto the freshly-built entries (see
  ``--reset-used`` in ``pipeline.py`` to opt out and re-enable
  everything).
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

# ``scripts/`` is on sys.path both when invoked directly and via
# pipeline.py, so the ``fscs`` subpackage imports resolve without a
# relative prefix.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from io_encoding import reconfigure_stdio_utf8  # noqa: E402

reconfigure_stdio_utf8()
from fscs import (  # noqa: E402
    FSCSBuildReport,
    FSCSBuildSkip,
    FSCSProject,
    build_fscs_document_with_report,
    load_fscs_json,
    save_fscs_json,
)


_REPORT_FILENAME = "fscs_generation_report.txt"


class FSCSGenerator:
    """Phase 1 orchestrator: input JSON → ``fscs.json`` + generation report.

    The ``config`` kwarg is preserved for callers that still pass the
    loaded ``project.json`` dict; this generator ignores it because
    project-tree mirroring is strictly Phase 2 / 3 business. Dropping
    the kwarg outright would churn every caller for zero gain.
    """

    def __init__(self, config: Optional[Dict] = None):
        self.config = config or {}

    def generate(
        self,
        input_path: Path,
        *,
        output_path_json: Optional[Path] = None,
        report_path: Optional[Path] = None,
        project: Optional[FSCSProject] = None,
        reset_used: bool = False,
        default_product_type: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Build ``fscs.json`` + generation report from one JSON input.

        :param input_path: ``inputs/*.json`` to load.
        :param output_path_json: Destination for ``fscs.json``. Defaults
            to ``outputs/fscs/fscs.json`` next to the report.
        :param report_path: Destination for the generation report.
            Defaults to ``outputs/fscs/fscs_generation_report.txt``. The
            report is always written, even on clean builds (``0 skipped``
            rows), so reviewers can diff successive runs.
        :param project: Optional :class:`FSCSProject` metadata echoed
            into the document.
        :param reset_used: When True, the ``used`` preservation step
            that normally carries operator selections forward from an
            existing ``fscs.json`` is skipped and every DID starts with
            ``used_22 = used_2e = True`` (the schema default). Plumbed
            through from ``pipeline.py --reset-used``.

        :return: Summary dict -- machine-readable echo of the report
            counts plus the paths written. Used by the pipeline for
            console summaries and by tests as a stable contract.
        """
        records = _load_records(input_path)

        if output_path_json is None:
            # Default location mirrors the downstream contract: Phase 2
            # and Phase 3 look for fscs.json at exactly this path.
            output_path_json = Path("outputs/fscs/fscs.json")
        if report_path is None:
            report_path = output_path_json.parent / _REPORT_FILENAME

        # Snapshot previous operator-owned fields *before* we write the
        # new JSON -- otherwise save_fscs_json below overwrites the very
        # file we're trying to read for preservation.
        preserved = self._snapshot_operator_state(output_path_json) \
            if (not reset_used and output_path_json.is_file()) else None

        print(f"Total records: {len(records)}")

        document, report = build_fscs_document_with_report(
            records,
            project=project,
            source_inputs=str(input_path),
            default_product_type=default_product_type,
        )

        carried = 0
        carried_behavior = 0
        if preserved:
            for did in document.dids:
                state = preserved.get(did.did_hex)
                if state is None:
                    continue
                u22, u2e, b22, b2e = state
                b22 = _normalise_behavior_text(b22)
                b2e = _normalise_behavior_text(b2e)
                did.service_22.used = u22
                did.service_2e.used = u2e
                if b22 is not None and did.service_22.behavior != b22:
                    carried_behavior += 1
                if b2e is not None and did.service_2e.behavior != b2e:
                    carried_behavior += 1
                if b22 is not None:
                    did.service_22.behavior = b22
                if b2e is not None:
                    did.service_2e.behavior = b2e
                if not (u22 and u2e):
                    carried += 1
            if carried:
                print(
                    f"Preserved {carried} operator selection(s) from "
                    f"existing {output_path_json.name}"
                )
            if carried_behavior:
                print(
                    f"Preserved {carried_behavior} service behavior field(s) from "
                    f"existing {output_path_json.name}"
                )

        # Effective = supported AND used (operator may have deselected).
        # The console prints both the raw schema counts and the
        # effective counts so operators can spot mass-deselection at a
        # glance.
        supported_22 = sum(1 for d in document.dids if d.service_22.supported)
        supported_2e = sum(1 for d in document.dids if d.service_2e.supported)
        effective_22 = sum(1 for d in document.dids if d.service_22.effective)
        effective_2e = sum(1 for d in document.dids if d.service_2e.effective)

        print(f"Kept: {report.kept_count}  "
              f"Filtered (supported_by_ecu=N): {report.filtered_count}  "
              f"Skipped (schema errors): {len(report.skipped)}")
        print(f"Service 22 (Read): supported={supported_22} effective={effective_22}")
        print(f"Service 2E (Write): supported={supported_2e} effective={effective_2e}")

        output_path_json.parent.mkdir(parents=True, exist_ok=True)
        save_fscs_json(document, output_path_json)

        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(
            _render_generation_report(
                input_path=input_path,
                output_json=output_path_json,
                report=report,
                preserved_used_count=carried,
                reset_used=reset_used,
            ),
            encoding="utf-8",
        )

        return {
            'total': report.total_count,
            'kept': report.kept_count,
            'filtered': report.filtered_count,
            'skipped': len(report.skipped),
            'supported_22': supported_22,
            'supported_2e': supported_2e,
            'effective_22': effective_22,
            'effective_2e': effective_2e,
            'preserved_used': carried,
            'preserved_behavior': carried_behavior,
            'output_path_json': str(output_path_json),
            'report_path': str(report_path),
            # Lists retained for the pipeline/console summary and tests;
            # unchanged vs. v1.0 semantics.
            'dids_22': [d.did_hex for d in document.dids if d.service_22.effective],
            'dids_2e': [d.did_hex for d in document.dids if d.service_2e.effective],
        }

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _snapshot_operator_state(
        fscs_json_path: Path,
    ) -> Optional[Dict[str, tuple]]:
        """Return operator-owned per-DID state from an existing fscs.json.

        Returns ``None`` and prints a warning when the file can't be
        parsed -- a corrupt pre-existing JSON must never block a fresh
        Phase 1 run, it's the very thing we're about to overwrite. This
        mirrors the v1.0 behaviour that defaulted ``used=True`` for
        every DID when preservation failed.
        """
        try:
            raw = json.loads(fscs_json_path.read_text(encoding="utf-8"))
            existing = load_fscs_json(fscs_json_path)
        except Exception as exc:  # noqa: BLE001 -- defensive
            print(
                f"WARNING: could not read existing {fscs_json_path} "
                f"to preserve selections ({exc}); all DIDs default to used=True."
            )
            return None
        raw_by_did = {
            str(entry.get("did_hex") or "").strip().upper(): entry
            for entry in raw.get("dids", [])
            if isinstance(entry, dict)
        }
        preserved = {}
        for entry in existing.dids:
            raw_entry = raw_by_did.get(entry.did_hex) or {}
            raw_22 = raw_entry.get("service_22") if isinstance(raw_entry, dict) else {}
            raw_2e = raw_entry.get("service_2e") if isinstance(raw_entry, dict) else {}
            has_b22 = isinstance(raw_22, dict) and "behavior" in raw_22
            has_b2e = isinstance(raw_2e, dict) and "behavior" in raw_2e
            preserved[entry.did_hex] = (
                entry.service_22.used,
                entry.service_2e.used,
                entry.service_22.behavior if has_b22 else None,
                entry.service_2e.behavior if has_b2e else None,
            )
        return preserved


def _autodiscover_input(inputs_dir: Path) -> Optional[Path]:
    """Pick the first ``*_did.json`` under ``inputs/`` (alphabetical).

    Phase 1 accepts ONLY schema-compliant ``inputs/<customer>_did.json``;
    operators who start from a questionnaire workbook must first run
    an agent-written ``.DCOM_AI/DID_Toolkit_PRJ/scripts/extract_<customer>.py`` to
    produce that JSON. See ``reference/excel-ingestion.md``.
    """
    if not inputs_dir.is_dir():
        return None
    json_candidates = sorted(
        p for p in inputs_dir.iterdir()
        if p.is_file() and p.suffix.lower() == ".json"
        and "did" in p.name.lower()
    )
    return json_candidates[0] if json_candidates else None


def _load_records(input_path: Path) -> List[Dict[str, Any]]:
    """Open ``input_path`` (a ``*_did.json``) and return the record list.

    ``.xlsx`` / ``.xlsm`` inputs are not accepted directly. Phase 1
    consumes ONLY schema-compliant ``*_did.json`` files matching
    ``reference/input-format.md``. Agents normalise any vendor
    questionnaire (.xlsx) by writing a one-off
    ``.DCOM_AI/DID_Toolkit_PRJ/scripts/extract_<customer>.py`` that emits the JSON.

    The returned list is exactly the shape
    :func:`build_fscs_document_with_report` accepts -- one dict per DID,
    keyed by the legacy snake_case names (``did_hex``, ``access``,
    ``sub_fields``, etc).
    """
    suffix = input_path.suffix.lower()
    if suffix != ".json":
        raise ValueError(
            f"Unsupported input file type: {input_path.name!r} (suffix "
            f"{suffix!r}). Phase 1 accepts only schema-compliant "
            "*_did.json; normalise any .xlsx questionnaire via a "
            ".DCOM_AI/DID_Toolkit_PRJ/scripts/extract_<customer>.py adapter first. "
            "See reference/excel-ingestion.md."
        )
    with open(input_path, "r", encoding="utf-8") as f:
        records = json.load(f)
    return records


def _normalise_behavior_text(text: Optional[str]) -> Optional[str]:
    """Collapse legacy per-line hardcode prefixes to one ``HardCode:`` header."""
    if text is None:
        return None
    lines = text.splitlines()
    non_empty = [line.strip() for line in lines if line.strip()]
    if not non_empty:
        return text
    prefix = "hardcode:"
    if all(line.lower().startswith(prefix) for line in non_empty):
        constants = [
            line[len(prefix):].strip()
            for line in non_empty
        ]
        return "HardCode:\n" + "\n".join(constants)
    return text


def _render_generation_report(
    *,
    input_path: Path,
    output_json: Path,
    report: FSCSBuildReport,
    preserved_used_count: int,
    reset_used: bool,
) -> str:
    """Format :class:`FSCSBuildReport` as the human-readable report file.

    The layout is intentionally stable (header + summary counts +
    per-section lists) so operators can ``diff`` successive runs to see
    what changed. The file is UTF-8 so CJK ``did_name_zh`` values stay
    legible on Windows terminals.
    """
    lines: List[str] = []
    lines.append("FSCS Generation Report")
    lines.append("=" * 70)
    lines.append(f"Generated at:  {datetime.now().isoformat(timespec='seconds')}")
    lines.append(f"Input file:    {input_path}")
    lines.append(f"Output JSON:   {output_json}")
    lines.append("")
    lines.append("Summary")
    lines.append("-" * 70)
    lines.append(f"  Total records in input        : {report.total_count}")
    lines.append(f"  Kept (written to fscs.json)   : {report.kept_count}")
    lines.append(f"  Filtered (supported_by_ecu=N) : {report.filtered_count}")
    lines.append(f"  Skipped (schema errors)       : {len(report.skipped)}")
    if preserved_used_count:
        lines.append(
            f"  Used flags preserved from prev fscs.json "
            f"(deselections): {preserved_used_count}"
        )
    if reset_used:
        lines.append(
            "  --reset-used active: previous used selections were "
            "discarded; all DIDs start with used=True."
        )
    lines.append("")

    if report.skipped:
        lines.append("Skipped records")
        lines.append("-" * 70)
        for skip in report.skipped:
            lines.extend(_format_skip_block(skip))
        lines.append("")
    else:
        lines.append("Skipped records: (none)")
        lines.append("")

    # Filtered-by-supported_by_ecu records are a business-as-usual
    # filter rather than an error; we only mention the count so the
    # report stays compact. Operators who need the specific list can
    # re-query the input JSON.
    lines.append(
        "Filter policy: records with supported_by_ecu != 'Y' are dropped "
        "silently. Only schema errors end up in the 'Skipped records' "
        "section above."
    )
    return "\n".join(lines) + "\n"


def _format_skip_block(skip: FSCSBuildSkip) -> List[str]:
    """Render one skipped record as a block of report lines."""
    did_label = f"${skip.did_hex}h" if skip.did_hex else "<missing did_hex>"
    header = f"  [{skip.index:03d}] {did_label}  (reason={skip.reason})"
    block = [header]
    # Each detail line is indented so the block visually belongs to its
    # header when scrolled past in a text editor.
    for detail in skip.details:
        block.append(f"        {detail}")
    return block


def main() -> None:
    parser = argparse.ArgumentParser(
        description='Generate the authoritative fscs.json from a schema-'
                    'compliant *_did.json input. FSCS_22.txt / FSCS_2E.txt '
                    'are not emitted here -- they are produced by '
                    'pipeline.py --phase xlsx-import once the operator has '
                    'reviewed the "used" selections. Direct Excel ingestion '
                    'is not supported; .xlsx questionnaires must first be '
                    'normalised into *_did.json by an agent-written '
                    '.DCOM_AI/DID_Toolkit_PRJ/scripts/extract_<customer>.py.'
    )
    parser.add_argument('--input', '-i', default=None,
                        help='Input file path. Must be a schema-compliant '
                             '*_did.json (see reference/input-format.md). '
                             'When omitted, the first inputs/*_did.json '
                             'in alphabetical order wins. Direct .xlsx / '
                             '.xlsm support is intentionally absent.')
    parser.add_argument('--output-json', default=None,
                        help='Authoritative fscs.json output. Defaults to '
                             'outputs/fscs/fscs.json.')
    parser.add_argument('--report', default=None,
                        help='Generation report path. Defaults to '
                             'outputs/fscs/fscs_generation_report.txt.')
    parser.add_argument('--reset-used', action='store_true',
                        help='Discard used flags from any pre-existing '
                             'fscs.json; the fresh build starts with '
                             'used_22 = used_2e = True for every DID.')
    parser.add_argument(
        '--product-type', default=None,
        help='When set, freshly-built DIDs whose source records carry '
             'no product_type (i.e. "applies to all products") are '
             'auto-stamped with this value. Single-product workflows '
             'pass --product-type DPB / ESP / ESPCL / IPB / RBU here '
             'to avoid having to fill the column in fscs_edit.xlsx. '
             'Has no effect on DIDs that were tagged in the input.',
    )
    args = parser.parse_args()

    input_path = Path(args.input) if args.input else _autodiscover_input(Path("inputs"))
    if input_path is None:
        parser.error(
            "no --input given and inputs/ contains no *_did.json; "
            "cannot continue. (Direct .xlsx ingestion is not supported; "
            "write a .DCOM_AI/DID_Toolkit_PRJ/scripts/extract_<customer>.py adapter to "
            "produce the *_did.json from a questionnaire.)"
        )

    print("Generating FSCS artefacts...")
    print("=" * 70)
    print(f"Input              : {input_path}")
    generator = FSCSGenerator()
    stats = generator.generate(
        input_path=input_path,
        output_path_json=Path(args.output_json) if args.output_json else None,
        report_path=Path(args.report) if args.report else None,
        reset_used=args.reset_used,
        default_product_type=args.product_type,
    )

    print("\n" + "=" * 70)
    print("Generation Complete")
    print("=" * 70)
    print(f"\nAuthoritative JSON : {stats['output_path_json']}")
    print(f"Generation report  : {stats['report_path']}")
    print(
        f"\nKept={stats['kept']}  "
        f"Filtered={stats['filtered']}  "
        f"Skipped={stats['skipped']}  "
        f"Total={stats['total']}"
    )


if __name__ == '__main__':
    main()
