"""Render an :class:`FSCSDocument` to JSON bytes or plaintext FSCS files.

Design notes
------------

FSCS ``.txt`` output has tab-aligned columns and a byte-offset state
machine that walks ``sub_fields`` to produce the Positive Response
Message table. Previous phase-6 refactoring consciously left FSCS on
f-strings (instead of migrating to Jinja2) because the layout is more
readable as imperative ``lines.append(...)`` than as templates riddled
with whitespace-control tags.

This module preserves that decision: pure Python rendering functions,
every helper stateless and unit-testable. The JSON side is a thin
wrapper around ``pydantic.BaseModel.model_dump_json``.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from decimal import Decimal, InvalidOperation
from typing import Iterable, List

from .schema import (
    DIDFscsEntry,
    FSCSDocument,
    FSCSSecurityLevel,
    FSCSServiceAccess,
    FSCSSubField,
    FSCSValueRangeComposite,
    FSCSValueRangeEnum,
    FSCSValueRangeNone,
    FSCSValueRangeNumeric,
)


SEPARATOR = "=" * 80
_DATA_RECORD_LABEL_PADDING = 4
_DATA_RECORD_LABEL_MIN_WIDTH = 16
_VALUE_RANGE_WRAP_WIDTH = 80


# Leading banner written at the top of every ``FSCS_*.txt`` file. It
# exists to remind human reviewers that the plaintext view is a
# *derived* artifact of ``outputs/fscs/fscs.json`` -- hand-editing the
# ``.txt`` will be silently overwritten on the next pipeline run.
#
# The banner is intentionally self-contained (no dynamic timestamp, no
# path interpolation) so golden-file diffs stay stable and byte-wise
# reproducible across machines.
TXT_HEADER = (
    "# "
    + ("=" * 78)
    + "\n"
    "# Generated from outputs/fscs/fscs.json -- do not edit this file by hand.\n"
    "#\n"
    "# Workflow:\n"
    "#   1. Edit outputs/fscs/fscs_edit.xlsx.\n"
    "#   2. Run `python scripts/pipeline.py --phase xlsx-import`.\n"
    "#   3. Re-run Phase 2 / Phase 3 to refresh downstream artefacts.\n"
    "# "
    + ("=" * 78)
    + "\n"
    "\n"
)


# ---------------------------------------------------------------------------
# JSON side
# ---------------------------------------------------------------------------


def render_fscs_json(doc: FSCSDocument) -> str:
    """Serialise an ``FSCSDocument`` to a pretty-printed JSON string.

    The output is deterministic (key order follows the pydantic field
    declaration order; indent is 2; trailing newline added) so golden
    file diffs stay stable across runs.
    """
    # pydantic preserves declared field order; mode='json' makes sure
    # tagged-union discriminators + enums come out as strings.
    data = doc.model_dump(mode="json")
    rendered = json.dumps(data, indent=2, ensure_ascii=False)
    if not rendered.endswith("\n"):
        rendered += "\n"
    return rendered


# ---------------------------------------------------------------------------
# TXT side
# ---------------------------------------------------------------------------


def render_fscs_22_txt(doc: FSCSDocument) -> str:
    """Render the Service 22 (Read) FSCS document for human review.

    A DID is emitted iff ``service_22.effective`` is ``True`` -- i.e.
    the DID structurally supports Read *and* the operator has not
    opted it out via ``used=False`` in the xlsx edit workbook. Each DID
    block is followed by the 80-``=`` separator to match the legacy
    generator's output.
    """
    return _render_txt(
        (did for did in doc.dids if did.service_22.effective),
        is_write=False,
    )


def render_fscs_2e_txt(doc: FSCSDocument) -> str:
    """Render the Service 2E (Write) FSCS document for human review.

    A DID is emitted iff ``service_2e.effective`` is ``True`` -- same
    gate as :func:`render_fscs_22_txt`, applied to the Write side.
    """
    return _render_txt(
        (did for did in doc.dids if did.service_2e.effective),
        is_write=True,
    )


def _render_txt(dids: Iterable[DIDFscsEntry], *, is_write: bool) -> str:
    blocks = [_render_did_block(did, is_write=is_write) for did in dids]
    # Legacy behaviour: joins per-DID blocks with a single ``\n`` and
    # each block ends with its own trailing ``\n``. We reproduce that
    # exactly so human diff tools stay tidy. The leading ``TXT_HEADER``
    # banner makes the "JSON is authoritative" contract explicit to
    # anyone skimming the .txt directly.
    return TXT_HEADER + "\n".join(blocks)


def _render_did_block(did: DIDFscsEntry, *, is_write: bool) -> str:
    lines: List[str] = []
    lines.append(f"Identifier ${did.did_hex}h - {did.did_name}")
    lines.append("")

    lines.append("Description")
    lines.append(_description_line(did, is_write=is_write))
    lines.append("")

    service = did.service_2e if is_write else did.service_22
    _append_availability(lines, service)
    lines.append("")

    _append_security(lines, service)
    lines.append("")

    _append_request_block(lines, did, is_write=is_write)
    lines.append("")

    _append_response_block(lines, did, is_write=is_write)
    lines.append("")

    _append_data_footer(lines, did, is_write=is_write)
    lines.append("")
    lines.append(SEPARATOR)
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Per-section helpers
# ---------------------------------------------------------------------------


def _description_line(did: DIDFscsEntry, *, is_write: bool) -> str:
    override = (
        did.free_text.description_write if is_write
        else did.free_text.description_read
    )
    if override is not None:
        return override
    verb = "writes" if is_write else "returns"
    return f"This identifier {verb} the {did.did_name}"


def _append_availability(lines: List[str], service: FSCSServiceAccess) -> None:
    lines.append("Availability")
    if service.sessions:
        lines.append("Supported in the following diagnostic sessions:")
        for session in service.sessions:
            lines.append(f"- {session}")
    else:
        lines.append("No diagnostic sessions supported.")


def _append_security(lines: List[str], service: FSCSServiceAccess) -> None:
    lines.append("Security Level:")
    if service.security_levels:
        for sl in service.security_levels:
            lines.append(f"\t\t{_format_security_level(sl)}")
    else:
        lines.append("\t\tNone")


def _format_security_level(sl: FSCSSecurityLevel) -> str:
    if sl.note:
        return f"{sl.level} {sl.note}"
    return sl.level


def _append_request_block(
    lines: List[str], did: DIDFscsEntry, *, is_write: bool
) -> None:
    lines.append("Request Message:")
    override = (
        did.free_text.request_block_2e if is_write
        else did.free_text.request_block_22
    )
    if override is not None:
        lines.extend(override.splitlines())
        return
    sid_byte = "$2E" if is_write else "$22"
    sid_name = (
        "WriteDataByIdentifier" if is_write else "ReadDataByIdentifier"
    )
    header_rows: List[tuple[str, str]] = [
        ("Byte 1", f'{sid_byte} = Request Service Id "{sid_name}"'),
        ("Byte 2-3", f"${did.did_hex} = {did.did_name}"),
    ]
    _append_byte_table(lines, did, header_rows, include_data=is_write)


def _append_response_block(
    lines: List[str], did: DIDFscsEntry, *, is_write: bool
) -> None:
    lines.append("Positive Response Message:")
    override = (
        did.free_text.response_block_2e if is_write
        else did.free_text.response_block_22
    )
    if override is not None:
        lines.extend(override.splitlines())
        return
    sid_byte = "$6E" if is_write else "$62"
    sid_name = (
        "WriteDataByIdentifier" if is_write else "ReadDataByIdentifier"
    )
    header_rows: List[tuple[str, str]] = [
        ("Byte 1", f'{sid_byte} = Response Service Id "{sid_name}"'),
        ("Byte 2-3", f"${did.did_hex} = {did.did_name}"),
    ]
    _append_byte_table(lines, did, header_rows, include_data=not is_write)


def _append_byte_table(
    lines: List[str],
    did: DIDFscsEntry,
    header_rows: List[tuple[str, str]],
    *,
    include_data: bool,
) -> None:
    """Render a header + optional data-record table sharing one column width.

    Aligning ``Byte 1`` / ``Byte 2-3`` with the data record rows keeps the
    request/response block visually consistent regardless of which DID we
    are looking at -- the column edge stays put even when one DID has
    short ``Byte N`` labels and another has long ``Byte 12-13 [bit 0-3]``
    annotations.
    """
    data_rows = _collect_data_rows(did) if include_data else []
    all_labels = [label for label, _ in header_rows]
    all_labels.extend(label for label, _, _ in data_rows)
    width = _data_record_label_width(all_labels)
    for label, text in header_rows:
        lines.append(_format_data_record_line(label, text, width))
    for label, name, aux_lines in data_rows:
        lines.append(_format_data_record_line(label, name, width))
        for aux in aux_lines:
            lines.append(_format_data_record_aux_line(aux, width))


def _collect_data_rows(
    did: DIDFscsEntry,
) -> List[tuple[str, str, List[str]]]:
    if not did.sub_fields:
        return []
    cursor_byte_did = 0
    shared_at: dict[int, int] = {}
    for sf in did.sub_fields:
        if sf.byte_idx is not None:
            cursor_byte_did = _bounded_byte_idx(sf.byte_idx, did.size_bytes)
        shared_at[cursor_byte_did] = shared_at.get(cursor_byte_did, 0) + 1
    rows: List[tuple[str, str, List[str]]] = []
    cursor_byte_did = 0
    for sf in did.sub_fields:
        if sf.byte_idx is not None:
            cursor_byte_did = _bounded_byte_idx(sf.byte_idx, did.size_bytes)
        byte_desc = _sub_field_byte_desc(
            sf, cursor_byte_did=cursor_byte_did, did_size=did.size_bytes,
            shared_count=shared_at.get(cursor_byte_did, 1),
        )
        rows.append((byte_desc, sf.name_en, _sub_field_aux_lines(sf)))
    return rows


def _data_record_label_width(byte_descs: Iterable[str]) -> int:
    longest = max((len(d) for d in byte_descs), default=0)
    return max(_DATA_RECORD_LABEL_MIN_WIDTH, longest + _DATA_RECORD_LABEL_PADDING)


def _sub_field_byte_desc(
    sf: FSCSSubField, *, cursor_byte_did: int, did_size: int, shared_count: int,
) -> str:
    """Compute a frame-level byte header, capped to the DID payload size."""
    frame_start = 4 + cursor_byte_did
    remaining = max(1, did_size - cursor_byte_did)
    span = min(max(1, sf.byte_span), remaining)
    if span > 1:
        desc = f"Byte {frame_start}-{frame_start + span - 1}"
    else:
        desc = f"Byte {frame_start}"
    bit = (sf.bit or "All").strip()
    if shared_count > 1 and bit.upper() != "ALL":
        desc = f"{desc} [bit {bit}]"
    return desc


def _bounded_byte_idx(raw: int, did_size: int) -> int:
    return min(max(0, raw), max(0, did_size - 1))


def _format_data_record_line(label: str, text: str, width: int) -> str:
    return f"{label:<{width}}{text}"


def _format_data_record_aux_line(text: str, width: int) -> str:
    return f"{'':<{width}}{text}"


def _sub_field_aux_lines(sf: FSCSSubField) -> List[str]:
    """Indented detail line(s) for a sub_field: enum mapping or range."""
    if sf.enum_mapping:
        parsed = _parse_enum_mapping(sf.enum_mapping)
        if parsed:
            return [f"{value}: {desc}" for value, desc in parsed]
    if sf.range_min and sf.range_max:
        return [f"Range: {_logical_raw_range_text(sf)}"]
    return []


def _parse_enum_mapping(raw: str) -> List["tuple[str, str]"]:
    """Split ``"0x00=Normal\\n0x01=Sport"`` into ``[(value, desc), ...]``.

    Accepts both ``"="`` and ``":"`` separators and single-space
    delimiters (so legacy mappings like ``"0x00 Normal"`` still parse).
    Returns an empty list for inputs we cannot make sense of; the
    caller then falls back to the numeric range branch.
    """
    out: List[tuple[str, str]] = []
    for line in raw.splitlines():
        line = line.strip()
        if not line:
            continue
        for sep in ("=", ":"):
            if sep in line:
                value, desc = line.split(sep, 1)
                out.append((value.strip(), desc.strip()))
                break
        else:
            parts = line.split(None, 1)
            if len(parts) == 2:
                out.append((parts[0], parts[1].strip()))
    return out


def _append_data_footer(
    lines: List[str], did: DIDFscsEntry, *, is_write: bool
) -> None:
    """Append the ``Data Type:`` / ``Storage:`` / ... footer block."""
    lines.append(f"Data Type:\t\t{did.data_type}")
    lines.append(f"Storage Position:\t{did.storage_position}")
    lines.append(f"Size:\t\t\t{did.size_bytes} bytes")
    # ``R/W State:`` is perspective-dependent in the .txt view: the
    # 22 doc always says "R", the 2E doc always says "W", even for
    # DIDs that are fundamentally RW. This matches the legacy output.
    lines.append(f"R/W State:\t\t{'W' if is_write else 'R'}")
    lines.append(f"NVM Item:\t\t{did.nvm_item}")
    value_range_lines = _format_value_range_lines(did)
    lines.append("Value Range:")
    for line in value_range_lines:
        lines.append(f"\t\t\t{line}")
    service = did.service_2e if is_write else did.service_22
    lines.append("Behavior:")
    if service.behavior:
        lines.extend(service.behavior.splitlines())


_VALUE_RANGE_CONTENT_INDENT = "    "


@dataclass
class _ValueRangeGroup:
    """Aggregates sub-fields into one byte (or byte-range) for footer rendering."""
    byte_idx: int | None
    byte_span: int
    enum_keys: List[str] = field(default_factory=list)
    numeric_lines: List[str] = field(default_factory=list)
    has_enum_member: bool = False

    @property
    def label(self) -> str:
        return _value_range_byte_label(self.byte_idx, self.byte_span)

    def add_enum_keys(self, keys: Iterable[str]) -> None:
        self.has_enum_member = True
        for k in keys:
            if k and k not in self.enum_keys:
                self.enum_keys.append(k)


def _format_value_range_lines(did: DIDFscsEntry) -> List[str]:
    """Render value ranges from current sub_fields, not stale summaries.

    Layout rules (M8):

    * Each byte group spans **two or more lines**: the first line is the
      bare ``Byte[i]:`` (or ``Byte[i-j]:``) label, the next lines carry
      the value content (physical range or merged enum list) indented by
      ``_VALUE_RANGE_CONTENT_INDENT`` so reviewers can scan the byte
      column and the value column independently.
    * **Enum bytes win over numeric bytes.** When a byte group contains
      *any* enum sub-field, only the merged enum keys are rendered --
      we never mix a sibling numeric sub-field's ``Physical range:`` in
      with the enum view, because the two describe different bit-fields
      and would visually collide.
    * Enum key lists are **interval-merged**. Consecutive keys
      ``0x00, 0x01, 0x02, 0x03`` collapse to ``0x00~0x03``; ranges the
      input already expressed as ``0x05-0x07`` are parsed back into
      intervals so they can chain with neighbouring singletons.
    * Numeric (non-enum) byte groups render
      ``Physical range: <min> ~ <max> [unit] (Resolution: r, Offset: o)``
      so the converted range stays self-documenting.
    """
    groups = _value_range_groups(did)
    if not groups:
        return _value_range_lines_from_summary(did)
    out: List[str] = []
    for group in groups:
        out.extend(_format_value_range_group(group))
    return out


def _value_range_lines_from_summary(did: DIDFscsEntry) -> List[str]:
    """Fallback when ``sub_fields`` are unavailable (e.g. TXT-imported docs).

    Same two-line layout as the structured path so reviewers see one
    consistent shape regardless of how the document was produced.
    """
    vr = did.value_range
    if isinstance(vr, FSCSValueRangeNone):
        return []
    label = f"{_value_range_byte_label(0, max(1, did.size_bytes))}:"
    if isinstance(vr, FSCSValueRangeNumeric):
        unit = f" {vr.unit}" if vr.unit else ""
        body = f"{vr.min} ~ {vr.max}{unit}".rstrip()
        return [label, f"{_VALUE_RANGE_CONTENT_INDENT}{body}"]
    if isinstance(vr, FSCSValueRangeEnum):
        merged = _merge_enum_keys(list(vr.values))
        return [label] + _wrap_indented(
            merged, indent=_VALUE_RANGE_CONTENT_INDENT, sep=", ",
        )
    if isinstance(vr, FSCSValueRangeComposite):
        text = (vr.rendered or "").replace("Enum: ", "").strip()
        if not text:
            return []
        segments = [s.strip() for s in text.split(";") if s.strip()]
        if not segments:
            segments = [text]
        return [label] + [
            f"{_VALUE_RANGE_CONTENT_INDENT}{seg}" for seg in segments
        ]
    return []


def _value_range_groups(did: DIDFscsEntry) -> List[_ValueRangeGroup]:
    groups: List[_ValueRangeGroup] = []
    by_byte: dict[int, _ValueRangeGroup] = {}
    cursor_byte_did = 0
    for sf in did.sub_fields:
        if sf.byte_idx is not None:
            cursor_byte_did = _bounded_byte_idx(sf.byte_idx, did.size_bytes)
        remaining = max(1, did.size_bytes - cursor_byte_did)
        span = min(max(1, sf.byte_span), remaining)
        if span > 1:
            group = _ValueRangeGroup(byte_idx=cursor_byte_did, byte_span=span)
            _populate_group(group, sf)
            if group.enum_keys or group.numeric_lines:
                groups.append(group)
            continue
        group = by_byte.get(cursor_byte_did)
        if group is None:
            group = _ValueRangeGroup(byte_idx=cursor_byte_did, byte_span=1)
            by_byte[cursor_byte_did] = group
            groups.append(group)
        _populate_group(group, sf)
    return [g for g in groups if g.enum_keys or g.numeric_lines]


def _populate_group(group: _ValueRangeGroup, sf: FSCSSubField) -> None:
    if sf.enum_mapping:
        keys = [v for v, _ in _parse_enum_mapping(sf.enum_mapping)]
        group.add_enum_keys(keys)
        return
    if sf.range_min and sf.range_max:
        group.numeric_lines.append(_physical_range_text(sf))


def _format_value_range_group(group: _ValueRangeGroup) -> List[str]:
    """Render one byte group as ``Byte[..]:`` + indented value lines.

    Enum bytes never inherit a sibling sub-field's ``Physical range:``
    (see ``_format_value_range_lines`` design notes for the rationale).
    """
    if group.has_enum_member:
        if not group.enum_keys:
            return []
        merged = _merge_enum_keys(group.enum_keys)
        return [f"{group.label}:"] + _wrap_indented(
            merged, indent=_VALUE_RANGE_CONTENT_INDENT, sep=", ",
        )
    if not group.numeric_lines:
        return []
    out: List[str] = [f"{group.label}:"]
    for line in group.numeric_lines:
        out.append(f"{_VALUE_RANGE_CONTENT_INDENT}{line}")
    return out


def _wrap_indented(
    values: List[str], *, indent: str, sep: str,
) -> List[str]:
    """Greedy-wrap ``values`` into one or more indented lines."""
    if not values:
        return []
    out: List[str] = []
    current = ""
    for v in values:
        candidate = v if not current else f"{current}{sep}{v}"
        if len(indent) + len(candidate) > _VALUE_RANGE_WRAP_WIDTH and current:
            out.append(f"{indent}{current}")
            current = v
        else:
            current = candidate
    if current:
        out.append(f"{indent}{current}")
    return out


def _merge_enum_keys(keys: List[str]) -> List[str]:
    """Collapse consecutive enum keys into ``0x**~0x**`` intervals.

    Keys may already be ranges (``"0x05-0x07"``) or singletons
    (``"0x00"`` / ``"5"``). All inputs are parsed into ``(lo, hi)``
    integer intervals, sorted, then merged when adjacent. Output is
    formatted in hex with width chosen so all values fit (2 chars for
    bytes, 4 for words, 8 for dwords). If any key fails to parse, we
    bail out and return the inputs unchanged so reviewers still see the
    raw data instead of silently dropping it.
    """
    intervals: List[tuple[int, int]] = []
    for raw in keys:
        parsed = _parse_enum_key_interval(raw)
        if parsed is None:
            return keys
        intervals.append(parsed)
    if not intervals:
        return []
    intervals.sort(key=lambda iv: (iv[0], iv[1]))
    merged: List[tuple[int, int]] = []
    for lo, hi in intervals:
        if merged and lo <= merged[-1][1] + 1:
            prev_lo, prev_hi = merged[-1]
            merged[-1] = (prev_lo, max(prev_hi, hi))
        else:
            merged.append((lo, hi))
    max_value = max(hi for _, hi in merged)
    if max_value <= 0xFF:
        width = 2
    elif max_value <= 0xFFFF:
        width = 4
    else:
        width = 8
    return [_format_hex_interval(lo, hi, width) for lo, hi in merged]


def _parse_enum_key_interval(raw: str) -> "tuple[int, int] | None":
    s = (raw or "").strip()
    if not s:
        return None
    for sep in ("~", "-", "–", "—"):
        if sep in s and not s.lower().startswith("0x" + sep):
            lo_str, _, hi_str = s.partition(sep)
            lo = _parse_hex_or_int(lo_str)
            hi = _parse_hex_or_int(hi_str)
            if lo is not None and hi is not None and hi >= lo:
                return (lo, hi)
            return None
    val = _parse_hex_or_int(s)
    if val is None:
        return None
    return (val, val)


def _parse_hex_or_int(raw: str) -> "int | None":
    s = (raw or "").strip()
    if not s:
        return None
    try:
        if s.lower().startswith("0x"):
            return int(s, 16)
        return int(s)
    except ValueError:
        return None


def _format_hex_interval(lo: int, hi: int, width: int) -> str:
    if lo == hi:
        return f"0x{lo:0{width}X}"
    return f"0x{lo:0{width}X}~0x{hi:0{width}X}"


def _logical_raw_range_text(sf: FSCSSubField) -> str:
    """Render the *logical* (raw register) range for a sub-field's ``Range:`` line.

    Heuristic precedence (M7):

    1. If both ``range_min`` / ``range_max`` are already hex literals
       (``0x...``), trust them verbatim -- the input expressed the
       logical view directly.
    2. Otherwise, derive logical = (physical - offset) / resolution and
       round to the nearest integer. Logical values are always
       byte-positioned bit-field codes; non-integer raw values are a
       computational artefact of imprecise resolutions, not real codes.
    3. Bail out to the literal physical strings only when the inputs
       cannot be parsed as decimals (so we don't lose the user's data).
    """
    if _is_hex_literal(sf.range_min) and _is_hex_literal(sf.range_max):
        return f"{sf.range_min} ~ {sf.range_max}"
    phy_min = _parse_logical_number(sf.range_min)
    phy_max = _parse_logical_number(sf.range_max)
    resolution = _parse_decimal(sf.resolution or "1")
    offset = _parse_decimal(sf.offset or "0")
    if (
        phy_min is None or phy_max is None or resolution is None
        or offset is None or resolution == 0
    ):
        return f"{sf.range_min} ~ {sf.range_max}"

    log_min = _round_to_integer((phy_min - offset) / resolution)
    log_max = _round_to_integer((phy_max - offset) / resolution)
    min_text = _logical_decimal_to_text(log_min, sf.byte_span)
    max_text = _logical_decimal_to_text(log_max, sf.byte_span)
    if min_text and max_text:
        return f"{min_text} ~ {max_text}"
    return f"{_format_decimal(log_min)} ~ {_format_decimal(log_max)}"


def _round_to_integer(value: Decimal) -> Decimal:
    """Half-up rounding to integer for raw register codes."""
    from decimal import ROUND_HALF_UP
    return value.quantize(Decimal("1"), rounding=ROUND_HALF_UP)


def _physical_range_text(sf: FSCSSubField) -> str:
    """Render ``Physical range: ...`` plus the inferred raw encoding.

    The trailing ``Encoded: Signed/Unsigned`` annotation lets reviewers
    immediately tell how the raw register is laid out without having to
    redo the ``(physical - offset) / resolution`` arithmetic in their
    head. Inference rule (M9): if the smallest raw value implied by the
    physical range is negative, the field is two's-complement signed;
    otherwise it is unsigned (with offset capturing any physical bias).
    """
    unit = f" {sf.unit}" if sf.unit else ""
    encoding = _infer_raw_encoding(sf)
    encoding_tag = f", Encoded: {encoding}" if encoding else ""
    return (
        f"Physical range: {sf.range_min} ~ {sf.range_max}{unit} "
        f"(Resolution: {sf.resolution or '1'}, Offset: {sf.offset or '0'}"
        f"{encoding_tag})"
    )


def _infer_raw_encoding(sf: FSCSSubField) -> str:
    """Return ``"Signed"`` / ``"Unsigned"`` / ``""`` for a sub-field's raw type.

    Returns the empty string when the inputs cannot be parsed -- the
    caller then drops the annotation entirely rather than guessing.
    """
    if not (sf.range_min and sf.range_max):
        return ""
    if _is_hex_literal(sf.range_min) and _is_hex_literal(sf.range_max):
        # Range is already expressed in raw hex -- no offset/resolution
        # information to derive signedness from.
        return ""
    phy_min = _parse_logical_number(sf.range_min)
    resolution = _parse_decimal(sf.resolution or "1")
    offset = _parse_decimal(sf.offset or "0")
    if phy_min is None or resolution is None or offset is None or resolution == 0:
        return ""
    raw_min = (phy_min - offset) / resolution
    return "Signed" if raw_min < 0 else "Unsigned"


def _parse_logical_number(raw: str | None) -> Decimal | None:
    if raw is None:
        return None
    value = raw.strip()
    try:
        if _is_hex_literal(value):
            return Decimal(int(value, 16))
        return Decimal(value)
    except (InvalidOperation, ValueError):
        return None


def _parse_decimal(raw: str | None) -> Decimal | None:
    if raw is None:
        return None
    try:
        return Decimal(str(raw).strip())
    except InvalidOperation:
        return None


def _format_decimal(value: Decimal) -> str:
    normalized = value.normalize()
    # Avoid scientific notation for reviewer-facing FSCS ranges.
    return format(normalized, "f")


def _is_hex_literal(raw: str | None) -> bool:
    return isinstance(raw, str) and raw.strip().lower().startswith("0x")


def _logical_decimal_to_text(number: Decimal, byte_span: int) -> str:
    """Render an integer logical/raw value as ``0xXXXX`` (or ``-0xXXXX``).

    Width tracks the field's byte span so a 2-byte field produces 4-digit
    hex literals (``0x0514``), keeping the column visually consistent.
    Negative values use a signed-magnitude prefix (``-0x003F``) rather
    than two's-complement bit pattern so reviewers can verify the
    conversion arithmetically without mentally subtracting ``2**N``.
    """
    if number != number.to_integral_value():
        return ""
    width = max(2, max(1, byte_span) * 2)
    n = int(number)
    if n < 0:
        return f"-0x{abs(n):0{width}X}"
    return f"0x{n:0{width}X}"


def _value_range_byte_label(byte_idx: int | None, byte_span: int) -> str:
    if byte_idx is None:
        return "Byte[?]"
    if byte_span <= 1:
        return f"Byte[{byte_idx}]"
    return f"Byte[{byte_idx}-{byte_idx + byte_span - 1}]"
